#!/bin/bash


if [ -z "${MAIN_DIR}" ]; then
    if [[ ${0} =~ ^/.+$ ]]; then
        export MAIN_DIR="$(dirname ${0})/../.."
    else
        export MAIN_DIR="${PWD}/$(dirname ${0})/../.."
    fi
fi

export PACKAGE="leechcraft"

# Uncomment if necessary:
export SFX="-0ppa2"

export RPKGD="+dfsg"


# Launch common script for setting variables
source "${MAIN_DIR}/Launchpad/setting_variables"


# Get old version
GetOldVersion


# Find new version
export DEVELOPER=0xd34df00d
export PROJECT=leechcraft
export VER_LIST=$(curl "https://github.com/${DEVELOPER}/${PROJECT}/tags" 2>&1 | sed -ne "s:^.*\"/${DEVELOPER}/${PROJECT}/archive/\(.*\).tar.gz\" .*:\1:p")
export CUR_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
export NEW_VER=${CUR_VER}${RPKGD}
export NEW_VER_FULL=${NEW_VER}${SFX}${UBUNTU_SFX}


# Display versions
DisplayVersions "https://github.com/${DEVELOPER}/${PROJECT}/tags"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get the sources
if [ ! -e "${PACKAGE}_${NEW_VER}.orig.tar.xz" ]; then
    "${PKG_DIR}/${PACKAGE}-debian/debian/rules" "get-orig-source"
fi


export UPDATE_STRING="Update to stable release ${CUR_VER}."

export DESTINATION="leechcraft-stable"

export DIST_LIST="saucy
                  raring"

export A_TYPE="xz"
export D_ARGS="xJf"

export EDIT_CHANGELOG="true"

# Launch common script for updating packages and uploading them to mentors.debian.net
source "${MAIN_DIR}/Launchpad/updating_packages"

