#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="psimedia"

# Uncomment if necessary:
export SFX="-3"

#export NEW_VER=1.0.3-git20130306-c2b8446

export A_TYPE="gz"


# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"


# Get old version
GetOldVersion


# Get new version
DEVELOPER=psi-im
PROJECT=psimedia
if GetNewVersion "${@}"; then
    VER_LIST=$(curl "https://github.com/${DEVELOPER}/${PROJECT}/releases" 2>&1 | sed -ne "s:^.*\"/${DEVELOPER}/${PROJECT}/archive/v\(.*\).tar.gz\" .*:\1:p")
    NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
fi
export NEW_VER_FULL=${NEW_VER}${SFX}


# Display versions
DisplayVersions "https://github.com/${DEVELOPER}/${PROJECT}/releases"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get sources
GetSources


# Launch common script for updating packages
source "${MAIN_DIR}/Debian/updating_packages"

