#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="freedcpp-mediapack"

# Uncomment if necessary:
export SFX="-0ppa2"

export NEW_VER="0.0.3"


# Launch common script for setting variables
source "${MAIN_DIR}/Launchpad/setting_variables"


# Get old version
GetOldVersion


# Find new version
export VER_LIST=$(curl 'http://code.google.com/p/freedcpp/downloads/' 2>&1 | sed -ne "s:^.*code.google.com/freedcpp/mediapack.\(.*\).tar.bz2\".*$:\1:p")
if [ -z "${NEW_VER}" ]; then
    export NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
fi
export NEW_VER_FULL=${NEW_VER}${SFX}${UBUNTU_SFX}


# Display versions
DisplayVersions "http://code.google.com/p/freedcpp/downloads/list"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get sources
if [ ! -e "${PACKAGE}_${NEW_VER}.orig.tar.${A_TYPE}" ]; then
    echo "Fix me!"
fi


export DESTINATION="direct-connect"

export DIR_NAME="mediapack"
export OLD_DIR_NAME="mediapack"

# Launch common script for updating packages and uploading them to Launchpad
source "${MAIN_DIR}/Launchpad/updating_packages"

