#!/bin/bash


export MAIN_DIR="${HOME}/WorkDir/Devel/deb_packages"

export PACKAGE="freedcpp-mediapack"

# Uncomment if necessary:
#export SFX="-0ppa2"


# Launch common script for setting variables
source "${MAIN_DIR}/Launchpad/setting_variables"


# Get old version
GetOldVersion


# Find new version
export VER_LIST=$(curl 'http://code.google.com/p/freedcpp/downloads/list' 2>&1 | grep 'freedcpp.googlecode.com/files/mediapack.' | grep '.tar.bz2"' | sed -e "s:^.*freedcpp.googlecode.com/files/mediapack.\(.*\).tar.bz2\".*$:\1:")
export NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
export NEW_VER_FULL=${NEW_VER}${SFX}${UBUNTU_SFX}


# Display versions
DisplayVersions "http://code.google.com/p/freedcpp/downloads/list"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get the sources
if !([ -e "mediapack.${NEW_VER}.tar.bz2" ]); then
    wget -4 "http://freedcpp.googlecode.com/files/mediapack.${NEW_VER}.tar.bz2"
    rm -rf "${PACKAGE}-${NEW_VER}"
    tar xjf "mediapack.${NEW_VER}.tar.bz2"
    mv mediapack "${PACKAGE}-${NEW_VER}"
    tar -cjf "${PACKAGE}_${NEW_VER}.orig.tar.bz2" "${PACKAGE}-${NEW_VER}"
fi


export UPDATE_STRING="Update to stable release ${NEW_VER}."

# Launch common script for updating packages and uploading them to Launchpad
source "${MAIN_DIR}/Launchpad/updating_packages"

