#!/bin/bash


if [ -z "${MAIN_DIR}" ]; then
    if [[ ${0} =~ ^/.+$ ]]; then
        export MAIN_DIR="$(dirname ${0})/../.."
    else
        export MAIN_DIR="${PWD}/$(dirname ${0})/../.."
    fi
fi

export PACKAGE="bosixnet"

# Uncomment if necessary:
#export BPO_SFX="~bpo70+2"

#export BPO_VER=1.6-2

export BASIC_VER=1.6-1

# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"
source "${MAIN_DIR}/Debian/setting_variables_for_backports"


# Get old version
GetOldVersion


# Set versions
SetVersions


# Display versions
DisplayVersions


# Get the sources
if [ ! -e "${PACKAGE}_${PKG_VER}.orig.tar.xz" ]; then
    dget -d http://ftp.de.debian.org/debian/pool/main/b/${PACKAGE}/${PACKAGE}_${PKG_VER_FULL}.dsc
fi

export A_TYPE="gz"
export D_ARGS="xzf"


# Launch common script for updating packages and uploading them to mentors.debian.net
source "${MAIN_DIR}/Debian/updating_packages_for_backports"

