#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="bosixnet"

# Uncomment if necessary:
#export BPO_SFX="~bpo70+2"

#export BPO_VER=1.8-1

export BASIC_VER=1.7-1

# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"
source "${MAIN_DIR}/Debian/setting_variables_for_backports"


# Get old version
GetOldVersion


# Set versions
SetVersions


# Display versions
DisplayVersions


# Get the sources
if [ ! -e "${PACKAGE}_${PKG_VER}.orig.tar.xz" ]; then
    dget -d http://ftp.de.debian.org/debian/pool/main/b/${PACKAGE}/${PACKAGE}_${PKG_VER_FULL}.dsc
fi

export A_TYPE="gz"
export D_ARGS="xzf"


# Launch common script for updating packages and uploading them to mentors.debian.net
source "${MAIN_DIR}/Debian/updating_packages_for_backports"

