#!/bin/bash


if [ -z "${MAIN_DIR}" ]; then
    if [[ ${0} =~ ^/.+$ ]]; then
        export MAIN_DIR="$(dirname ${0})/../.."
    else
        export MAIN_DIR="${PWD}/$(dirname ${0})/../.."
    fi
fi

export PACKAGE="leechcraft-unstable"

# Uncomment if necessary:
#export SFX="-0ppa3"

export RPKGD="+dfsg"

#export CUR_VER=0.4.90-744-gda59196


# Launch common script for setting variables
source "${MAIN_DIR}/Launchpad/setting_variables"


# Get old version
GetOldVersion
export OLD_COMMIT=$(echo ${OLD_VER} | sed -e "s/^.*-[0-9]\+-g\(.*\)$/\1/" | sed 's/\+dfsg//')


# Find new version
GIT_REPO_DIR="${HOME}/WorkDir/Devel/LeechCraft/leechcraft_orig"
if [ -d "${GIT_REPO_DIR}" ]; then
    cd "${GIT_REPO_DIR}" || exit 1
    git pull --all || exit 1
fi
export LAST_COMMIT=$(git show -s --pretty=format:%h)
if [ -z "${NEW_VER}" ]; then
    export CUR_VER=$(git describe --tags | sed -e "s/^v\(.*\)$/\1/")
    export NEW_VER=${CUR_VER}${RPKGD}
fi
export NEW_VER_FULL=${NEW_VER}${SFX}${UBUNTU_SFX}
cd "${TEMP_DIR}" || exit 1


# Display versions
DisplayVersionsUnstable


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get the sources
if [ ! -e "${PACKAGE}_${NEW_VER}.orig.tar.xz" ]; then
    rm -rf  "${PACKAGE}-${NEW_VER}"
    # sources
    mkdir "${PACKAGE}-${NEW_VER}" || exit 1
    rsync -a "${GIT_REPO_DIR}/" "${PACKAGE}-${NEW_VER}/" --exclude=".git*" || exit 1
    # deleting some files and directories
    rm -r "${PACKAGE}-${NEW_VER}"/src/plugins/cstp/resources/images/clients/*
    rm -r "${PACKAGE}-${NEW_VER}"/src/plugins/advancednotifications/share/sounds/*
    mv "${PACKAGE}-${NEW_VER}"/src/plugins/azoth/share/azoth/iconsets/clients/default/unknown.png \
       "${PACKAGE}-${NEW_VER}"/src/plugins/azoth/share/azoth/iconsets/clients/unknown.png
    rm "${PACKAGE}-${NEW_VER}"/src/plugins/azoth/share/azoth/iconsets/clients/default/*
    mv "${PACKAGE}-${NEW_VER}"/src/plugins/azoth/share/azoth/iconsets/clients/unknown.png \
       "${PACKAGE}-${NEW_VER}"/src/plugins/azoth/share/azoth/iconsets/clients/default/unknown.png
    # tarball
    tar -cJf "${PACKAGE}_${NEW_VER}.orig.tar.xz" "${PACKAGE}-${NEW_VER}"
fi


export UPDATE_STRING="Minor update from Git ${BRANCH} branch."

export DESTINATION="leechcraft-unstable"

export DIST_LIST="raring
                  quantal"

export A_TYPE="xz"
export D_ARGS="xJf"

# Launch common script for updating packages and uploading them to mentors.debian.net
source "${MAIN_DIR}/Launchpad/updating_packages"

