#!/bin/sh

# Test Internet connection:
host github.com > /dev/null || exit 1

export MAIN_DIR="$(dirname $(realpath -s ${0}))"

export HTML_FILE="${MAIN_DIR}/docs/deb-packages.html"
export TMP_FILE="${HTML_FILE}.tmp"

export PROJECT_YEARS="2012-$(date +%Y)"

echo "HTML_FILE = ${HTML_FILE}"

rm -f "${TMP_FILE}"
echo "<html>" >> "${TMP_FILE}"
echo "<head>" >> "${TMP_FILE}"
echo "<meta content=\"text/html;\" http-equiv=\"content-type\">" >> "${TMP_FILE}"
echo "<meta content=\"Boris Pek\" name=\"author\">" >> "${TMP_FILE}"
echo "<meta content=\"Tehnick (c) ${PROJECT_YEARS}\" name=\"copyright\">" >> "${TMP_FILE}"
echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">" >> "${TMP_FILE}"
echo "<title>Packages overview for Boris Pek</title>" >> "${TMP_FILE}"
echo "</head>" >> "${TMP_FILE}"
echo "<body>" >> "${TMP_FILE}"

echo "<div id=\"header\" style=\"text-align: center;\">" >> "${TMP_FILE}"
echo "Packages overview for Boris Pek" >> "${TMP_FILE}"
echo "</div>" >> "${TMP_FILE}"
echo "<br>" >> "${TMP_FILE}"

echo "<div id=\"mainText\">" >> "${TMP_FILE}"
echo "<div id=\"statText\">" >> "${TMP_FILE}"

DATE_TIME=$(date "+%Y-%m-%d %H:%M:%S")
echo "<b>Last update:</b> ${DATE_TIME}<br>" >> "${TMP_FILE}"
echo "<br>" >> "${TMP_FILE}"


cd "${MAIN_DIR}"/Debian/
PACKAGES_NUMBER=$(ls */automatic_update_* | wc -l)
echo "<b>Debian (${PACKAGES_NUMBER}):</b>" >> "${TMP_FILE}"

echo "<div id=\"stat\">" >> "${TMP_FILE}"
echo "<table id=\"Debian\">" >> "${TMP_FILE}"
echo "<thead>" >> "${TMP_FILE}"
echo "<tr>" >> "${TMP_FILE}"
echo "<th width=\"30%\">" >> "${TMP_FILE}"
echo "Source Name" >> "${TMP_FILE}"
echo "</th>" >> "${TMP_FILE}"
echo "<th width=\"30%\">" >> "${TMP_FILE}"
echo "Old version" >> "${TMP_FILE}"
echo "</th>" >> "${TMP_FILE}"
echo "<th width=\"30%\">" >> "${TMP_FILE}"
echo "New version" >> "${TMP_FILE}"
echo "</th>" >> "${TMP_FILE}"
echo "<th width=\"10%\">" >> "${TMP_FILE}"
echo "Links" >> "${TMP_FILE}"
echo "</th>" >> "${TMP_FILE}"
echo "</tr>" >> "${TMP_FILE}"
echo "</thead>" >> "${TMP_FILE}"
echo "<tbody>" >> "${TMP_FILE}"

for PACKAGE in * ; do
    PKG_DIR="${MAIN_DIR}/Debian/${PACKAGE}"
    if [ ! -e "${PKG_DIR}/automatic_update_${PACKAGE}" ]; then continue; fi
    if [ "${TR}" = "<tr>" ]; then
        TRC="<tr>"
        TR="<tr class=\"color-odd\">"
    else
        TR="<tr>"
        TRC="<tr class=\"color-odd\">"
    fi
    echo;
    echo "Begin ${PACKAGE}"
    echo "${TR}" >> "${TMP_FILE}"
    "${PKG_DIR}/automatic_update_${PACKAGE}" "print-versions" "${TMP_FILE}"
    echo "</tr>" >> "${TMP_FILE}"
    echo "End ${PACKAGE}"
done

echo "</tbody>" >> "${TMP_FILE}"
echo "</table>" >> "${TMP_FILE}"
echo "</div>" >> "${TMP_FILE}"
echo "<br>" >> "${TMP_FILE}"
TR=""

cd "${MAIN_DIR}"/Launchpad/
PACKAGES_NUMBER=$(ls */automatic_update_* | wc -l)
echo "<b>Launchpad (${PACKAGES_NUMBER}):</b>" >> "${TMP_FILE}"

echo "<div id=\"stat\">" >> "${TMP_FILE}"
echo "<table id=\"Launchpad\">" >> "${TMP_FILE}"
echo "<thead>" >> "${TMP_FILE}"
echo "<tr class=\"color-odd\">" >> "${TMP_FILE}"
echo "<th width=\"30%\">" >> "${TMP_FILE}"
echo "Source Name" >> "${TMP_FILE}"
echo "</th>" >> "${TMP_FILE}"
echo "<th width=\"30%\">" >> "${TMP_FILE}"
echo "Old version" >> "${TMP_FILE}"
echo "</th>" >> "${TMP_FILE}"
echo "<th width=\"30%\">" >> "${TMP_FILE}"
echo "New version" >> "${TMP_FILE}"
echo "</th>" >> "${TMP_FILE}"
echo "<th width=\"10%\">" >> "${TMP_FILE}"
echo "Links" >> "${TMP_FILE}"
echo "</th>" >> "${TMP_FILE}"
echo "</tr>" >> "${TMP_FILE}"
echo "</thead>" >> "${TMP_FILE}"
echo "<tbody>" >> "${TMP_FILE}"

for PACKAGE in * ; do
    PKG_DIR="${MAIN_DIR}/Launchpad/${PACKAGE}"
    if [ ! -e "${PKG_DIR}/automatic_update_${PACKAGE}" ]; then continue; fi
    if [ "${TR}" = "<tr>" ]; then
        TRC="<tr>"
        TR="<tr class=\"color-odd\">"
    else
        TR="<tr>"
        TRC="<tr class=\"color-odd\">"
    fi
    echo;
    echo "Begin ${PACKAGE}"
    echo "${TR}" >> "${TMP_FILE}"
    "${PKG_DIR}/automatic_update_${PACKAGE}" "print-versions" "${TMP_FILE}"
    echo "</tr>" >> "${TMP_FILE}"
    echo "End ${PACKAGE}"
done

echo "</tbody>" >> "${TMP_FILE}"
echo "</table>" >> "${TMP_FILE}"
echo "</div>" >> "${TMP_FILE}"
echo "<br>" >> "${TMP_FILE}"

echo "<b>See also:</b>" >> "${TMP_FILE}"
echo "<a href=\"https://qa.debian.org/developer.php?login=Boris%20Pek\">qa.debian.org</a>" >> "${TMP_FILE}"
echo "<a href=\"./popcon-stat.html\">popcon-stat</a>" >> "${TMP_FILE}"
echo "<br>" >> "${TMP_FILE}"
echo "<br>" >> "${TMP_FILE}"
echo "</div>" >> "${TMP_FILE}"
echo "</div>" >> "${TMP_FILE}"

echo "<div id=\"footer\">" >> "${TMP_FILE}"
echo "Boris Pek &copy; ${PROJECT_YEARS}" >> "${TMP_FILE}"
echo "</div>" >> "${TMP_FILE}"

echo "</body>" >> "${TMP_FILE}"
echo "</html>" >> "${TMP_FILE}"
echo "" >> "${TMP_FILE}"
mv -f "${TMP_FILE}" "${HTML_FILE}"

if [ "${1}" = "open" ]; then
    xdg-open "${TMP_FILE}" &
fi

