#!/bin/sh

export MAIN_DIR="${HOME}/WorkDir/Devel/deb_packages"

echo "MAIN_DIR = ${MAIN_DIR}"
echo " "

# elmerfem
for PACKAGE in eiskaltdcpp-unstable uhub-unstable q4wine-unstable \
               freedcpp-unstable psi-plus-l10n qxmpp-unstable
do
    echo "Begin ${PACKAGE}"
    "${MAIN_DIR}/Launchpad/${PACKAGE}/automatic_update_${PACKAGE}" fast
    echo "End ${PACKAGE}"
    echo " "
done

