#!/bin/bash

export MAIN_DIR="${HOME}/WorkDir/Devel/deb_packages"

export POPCON_DATA_DIR="${MAIN_DIR}/Popcon"

echo "POPCON_DATA_DIR = ${POPCON_DATA_DIR}"

export HTML_FILE="${MAIN_DIR}/popcon-stat.html"

echo "HTML_FILE = ${HTML_FILE}"

if [ "${1}" != "local" ]; then
    rm -rf "${POPCON_DATA_DIR}"/*
    # Download data files
    mkdir -p "${POPCON_DATA_DIR}/Debian"
    cd "${POPCON_DATA_DIR}/Debian"
    wget -4 -c "http://popcon.debian.org/by_inst.gz"
    gzip -d by_inst.gz
    #
    mkdir -p "${POPCON_DATA_DIR}/Ubuntu"
    cd "${POPCON_DATA_DIR}/Ubuntu"
    wget -4 -c "http://popcon.ubuntu.com/by_inst.gz"
    gzip -d by_inst.gz
fi

cd "${MAIN_DIR}"

# Update file

echo "<html>" > "${HTML_FILE}"
echo "<head>" >> "${HTML_FILE}"
echo "<meta content=\"text/html;\" http-equiv=\"content-type\">" >> "${HTML_FILE}"
echo "<meta content=\"Boris Pek\" name=\"author\">" >> "${HTML_FILE}"
echo "<meta content=\"Tehnick (c) 2012\" name=\"copyright\">" >> "${HTML_FILE}"
echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">" >> "${HTML_FILE}"
echo "<title>Statistics of packages maintained by Boris Pek</title>" >> "${HTML_FILE}"
echo "</head>" >> "${HTML_FILE}"
echo "<body>" >> "${HTML_FILE}"

echo "<div id=\"header\" style=\"text-align: center;\">" >> "${HTML_FILE}"
echo "Statistics of packages maintained by Boris Pek" >> "${HTML_FILE}"
echo "</div>" >> "${HTML_FILE}"
echo "<br>" >> "${HTML_FILE}"

echo "<div id=\"mainText\">" >> "${HTML_FILE}"
echo "<div id=\"statText\">" >> "${HTML_FILE}"

DATE_TIME=$(date "+%Y-%m-%d %H:%M:%S")
echo "<b>Last update:</b> ${DATE_TIME}<br>" >> "${HTML_FILE}"
echo "<br>" >> "${HTML_FILE}"


PACKAGES_LIST=$(grep "Source: " "${MAIN_DIR}"/*/*/*-debian/debian/control | sed -e "s|^.*Source: \(.*\)$|\1|" | sort | uniq)
PACKAGES_NUMBER=$(echo "${PACKAGES_LIST}" | wc -l)
echo "<b>There are ${PACKAGES_NUMBER} packages for Debian and Ubuntu:</b>" >> "${HTML_FILE}"


echo "<div id=\"stat\">" >> "${HTML_FILE}"
echo "<table id=\"Stat\">" >> "${HTML_FILE}"
echo "<thead>" >> "${HTML_FILE}"
echo "<tr>" >> "${HTML_FILE}"
echo "<th>" >> "${HTML_FILE}"
echo "Source Name" >> "${HTML_FILE}"
echo "</th>" >> "${HTML_FILE}"
echo "<th>" >> "${HTML_FILE}"
echo "Package" >> "${HTML_FILE}"
echo "</th>" >> "${HTML_FILE}"
echo "<th>" >> "${HTML_FILE}"
echo "Number of packages installed in Debian" >> "${HTML_FILE}"
echo "</th>" >> "${HTML_FILE}"
echo "<th>" >> "${HTML_FILE}"
echo "Number of packages installed in Ubuntu" >> "${HTML_FILE}"
echo "</th>" >> "${HTML_FILE}"
echo "</tr>" >> "${HTML_FILE}"
echo "</thead>" >> "${HTML_FILE}"
echo "<tbody>" >> "${HTML_FILE}"


for PACKAGE in ${PACKAGES_LIST} ; do
    echo;
    echo "Begin ${PACKAGE}"
    #
    PKG_LIST=$(grep "Package: " "${MAIN_DIR}"/*/${PACKAGE}/${PACKAGE}-debian/debian/control | sed -e "s|^.*Package: \(.*\)$|\1|" | sort | uniq)
    FIRST_LINE=true
    for PKG in ${PKG_LIST} ; do
        PKG_INST_DEBIAN=$(grep " ${PKG} " "${POPCON_DATA_DIR}/Debian/by_inst" | awk '{print $3}')
        PKG_INST_UBUNTU=$(grep " ${PKG} " "${POPCON_DATA_DIR}/Ubuntu/by_inst" | awk '{print $3}')
        if [ "${TD}" = "<td>" ]; then
            TDC="<td>"
            TD="<td class=\"color-odd\">"
        else
            TD="<td>"
            TDC="<td class=\"color-odd\">"
        fi
        if [ "${FIRST_LINE}" = "true" ]; then
            FIRST_LINE=false
            echo "<tr class=\"td-separator\">" >> "${HTML_FILE}"
            echo "<td style=\"font-weight: bold;\">" >> "${HTML_FILE}"
            echo "${PACKAGE}" >> "${HTML_FILE}"
            echo "(<a href=\"http://packages.qa.debian.org/${PACKAGE}\">PTS</a>" >> "${HTML_FILE}"
            echo "<a href=\"https://launchpad.net/ubuntu/+source/${PACKAGE}\">LP</a>)" >> "${HTML_FILE}"
        else
            echo "<tr>" >> "${HTML_FILE}"
            echo "<td>" >> "${HTML_FILE}"
        fi
        echo "</td>" >> "${HTML_FILE}"
        echo "${TD}" >> "${HTML_FILE}"
        echo "${PKG}" >> "${HTML_FILE}"
        echo "</td>" >> "${HTML_FILE}"
        echo "${TD}" >> "${HTML_FILE}"
        echo "<a href=\"http://qa.debian.org/popcon-graph.php?packages=${PKG}&show_installed=on&want_legend=on&want_ticks=on&date_fmt=%25Y-%25m&beenhere=1\">${PKG_INST_DEBIAN}</a>" >> "${HTML_FILE}"
        echo "</td>" >> "${HTML_FILE}"
        echo "${TD}" >> "${HTML_FILE}"
        echo "<a href=\"http://popcon2.net/package/${PKG}.html#graph-1\">${PKG_INST_UBUNTU}</a>" >> "${HTML_FILE}"
        echo "</td>" >> "${HTML_FILE}"
        echo "</tr>" >> "${HTML_FILE}"
    done
    #
    echo "End ${PACKAGE}"
done

echo "</tbody>" >> "${HTML_FILE}"
echo "</table>" >> "${HTML_FILE}"
echo "</div>" >> "${HTML_FILE}"
echo "<br>" >> "${HTML_FILE}"


echo "<b>See also:</b>" >> "${HTML_FILE}"
echo "<a href=\"http://qa.debian.org/developer.php?login=Boris%20Pek\">qa.debian.org</a>" >> "${HTML_FILE}"
echo "<a href=\"./deb-packages.html\">deb-packages</a>" >> "${HTML_FILE}"
echo "<br>" >> "${HTML_FILE}"
echo "<br>" >> "${HTML_FILE}"
echo "</div>" >> "${HTML_FILE}"
echo "</div>" >> "${HTML_FILE}"

echo "<div id=\"footer\">" >> "${HTML_FILE}"
echo "Boris Pek &copy; 2012" >> "${HTML_FILE}"
echo "</div>" >> "${HTML_FILE}"

echo "</body>" >> "${HTML_FILE}"
echo "</html>" >> "${HTML_FILE}"
echo "" >> "${HTML_FILE}"

if [ "${1}" = "open" ]; then
    xdg-open "${HTML_FILE}" &
fi

