#!/bin/bash

# Test Internet connection:
host github.com > /dev/null || exit 1

export MAIN_DIR="${HOME}/WorkDir/Devel/deb_packages"

export POPCON_DATA_DIR="${MAIN_DIR}/Popcon"

echo "POPCON_DATA_DIR = ${POPCON_DATA_DIR}"

export HTML_FILE="${MAIN_DIR}/docs/popcon-stat.html"
export TMP_FILE="${HTML_FILE}.tmp"

export PROJECT_YEARS="2012-$(date +%Y)"

echo "TMP_FILE = ${TMP_FILE}"
echo ;

if [ "${1}" != "local" ]; then
    rm -rf "${POPCON_DATA_DIR}"/*
    # Debian
    GZ_FILE="http://popcon.debian.org/by_inst.gz"
    mkdir -p "${POPCON_DATA_DIR}/Debian"
    cd "${POPCON_DATA_DIR}/Debian"
    echo "${GZ_FILE}"
    curl -I "${GZ_FILE}" 2> /dev/null | grep "Last-Modified"
    wget -c "${GZ_FILE}"
    gzip -d by_inst.gz
    echo ;
    # Ubuntu
    GZ_FILE="http://popcon.ubuntu.com/by_inst.gz"
    mkdir -p "${POPCON_DATA_DIR}/Ubuntu"
    cd "${POPCON_DATA_DIR}/Ubuntu"
    echo "${GZ_FILE}"
    curl -I "${GZ_FILE}" 2> /dev/null | grep "Last-Modified"
    wget -c "${GZ_FILE}"
    gzip -d by_inst.gz
    echo ;
fi

cd "${MAIN_DIR}"

rm -f "${TMP_FILE}"
echo "<html>" >> "${TMP_FILE}"
echo "<head>" >> "${TMP_FILE}"
echo "<meta content=\"text/html;\" http-equiv=\"content-type\">" >> "${TMP_FILE}"
echo "<meta content=\"Boris Pek\" name=\"author\">" >> "${TMP_FILE}"
echo "<meta content=\"Tehnick (c) ${PROJECT_YEARS}\" name=\"copyright\">" >> "${TMP_FILE}"
echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">" >> "${TMP_FILE}"
echo "<title>Statistics of packages maintained by Boris Pek</title>" >> "${TMP_FILE}"
echo "</head>" >> "${TMP_FILE}"
echo "<body>" >> "${TMP_FILE}"

echo "<div id=\"header\" style=\"text-align: center;\">" >> "${TMP_FILE}"
echo "Statistics of packages maintained by Boris Pek" >> "${TMP_FILE}"
echo "</div>" >> "${TMP_FILE}"
echo "<br>" >> "${TMP_FILE}"

echo "<div id=\"mainText\">" >> "${TMP_FILE}"
echo "<div id=\"statText\">" >> "${TMP_FILE}"

PAGE_DATE_TIME=$(date "+%Y-%m-%d %H:%M:%S")
echo "<b>Page was generated:</b> ${PAGE_DATE_TIME}<br>" >> "${TMP_FILE}"
echo "<br>" >> "${TMP_FILE}"


PACKAGES_LIST=$(grep "Source: " "${MAIN_DIR}"/*/*/*-debian/debian/control | sed -e "s|^.*Source: \(.*\)$|\1|" | grep -v '\-devel' | grep -v '\-unstable' | grep -v '\-qt4' | sort | uniq)
PACKAGES_NUMBER=$(echo "${PACKAGES_LIST}" | wc -l)
echo "<b>There are ${PACKAGES_NUMBER} packages for Debian and Ubuntu with available statistics:</b>" >> "${TMP_FILE}"


echo "<div id=\"stat\">" >> "${TMP_FILE}"
echo "<table id=\"Stat\">" >> "${TMP_FILE}"
echo "<thead>" >> "${TMP_FILE}"
echo "<tr>" >> "${TMP_FILE}"
echo "<th>" >> "${TMP_FILE}"
echo "Source Name" >> "${TMP_FILE}"
echo "</th>" >> "${TMP_FILE}"
echo "<th>" >> "${TMP_FILE}"
echo "Links" >> "${TMP_FILE}"
echo "</th>" >> "${TMP_FILE}"
echo "<th>" >> "${TMP_FILE}"
echo "Package" >> "${TMP_FILE}"
echo "</th>" >> "${TMP_FILE}"
echo "<th title=\"Number of packages installed in Debian\">" >> "${TMP_FILE}"
echo "Debian Popcon" >> "${TMP_FILE}"
echo "</th>" >> "${TMP_FILE}"
echo "<th title=\"Number of packages installed in Ubuntu\">" >> "${TMP_FILE}"
echo "Ubuntu Popcon" >> "${TMP_FILE}"
echo "</th>" >> "${TMP_FILE}"
echo "<th>" >> "${TMP_FILE}"
echo "Links" >> "${TMP_FILE}"
echo "</th>" >> "${TMP_FILE}"
echo "</tr>" >> "${TMP_FILE}"
echo "</thead>" >> "${TMP_FILE}"
echo "<tbody>" >> "${TMP_FILE}"


for PACKAGE in ${PACKAGES_LIST} ; do
    echo;
    echo "Begin ${PACKAGE}"
    #
    PKG_LIST=$(grep "Package: " "${MAIN_DIR}"/*/${PACKAGE}/${PACKAGE}-debian/debian/control | sed -e "s|^.*Package: \(.*\)$|\1|" | sort | uniq)
    FIRST_LINE=true
    for PKG in ${PKG_LIST} ; do
        PKG_INST_DEBIAN="&ndash;"
        PKG_INST_UBUNTU="&ndash;"
        PKG_INFO_DEBIAN=$(grep -a " ${PKG} " "${POPCON_DATA_DIR}/Debian/by_inst")
        PKG_INFO_UBUNTU=$(grep -a " ${PKG} " "${POPCON_DATA_DIR}/Ubuntu/by_inst")
        if [ ! -z "${PKG_INFO_DEBIAN}" ]; then
            PKG_INST_DEBIAN=$(echo "${PKG_INFO_DEBIAN}" | awk '{print $3}')
        fi
        if [ ! -z "${PKG_INFO_UBUNTU}" ]; then
            PKG_INST_UBUNTU=$(echo "${PKG_INFO_UBUNTU}" | awk '{print $3}')
        fi  
        if [ "${TD}" = "<td>" ]; then
            TDC="<td>"
            TD="<td class=\"color-odd\">"
        else
            TD="<td>"
            TDC="<td class=\"color-odd\">"
        fi
        if [ "${FIRST_LINE}" = "true" ]; then
            FIRST_LINE=false
            echo "<tr class=\"td-separator\">" >> "${TMP_FILE}"
            echo "<td style=\"font-weight: bold;\">" >> "${TMP_FILE}"
            echo "${PACKAGE}" >> "${TMP_FILE}"
            echo "</td>" >> "${TMP_FILE}"
            echo "<td>" >> "${TMP_FILE}"
            echo "<a href=\"https://tracker.debian.org/pkg/${PACKAGE}\">PTS</a>" >> "${TMP_FILE}"
            echo "<a href=\"https://launchpad.net/ubuntu/+source/${PACKAGE}\">LP</a>" >> "${TMP_FILE}"
        else
            echo "<tr>" >> "${TMP_FILE}"
            echo "<td>" >> "${TMP_FILE}"
            echo "</td>" >> "${TMP_FILE}"
            echo "<td>" >> "${TMP_FILE}"
        fi
        echo "</td>" >> "${TMP_FILE}"
        echo "${TD}" >> "${TMP_FILE}"
        echo "${PKG}" >> "${TMP_FILE}"
        echo "</td>" >> "${TMP_FILE}"
        echo "${TD}" >> "${TMP_FILE}"
        echo "<a href=\"https://qa.debian.org/popcon-png.php?packages=${PKG}&show_installed=1&show_vote=0&show_old=0&show_recent=0&show_nofiles=0&want_percent=0&want_legend=1&want_ticks=0&date_fmt=%25Y-%25m\">${PKG_INST_DEBIAN}</a>" >> "${TMP_FILE}"
        echo "</td>" >> "${TMP_FILE}"
        echo "${TD}" >> "${TMP_FILE}"
        echo "<a href=\"http://ubuntu-popcon.43-1.org/cgi-bin/graph.pl?name=${PKG}\">${PKG_INST_UBUNTU}</a>" >> "${TMP_FILE}"
        echo "</td>" >> "${TMP_FILE}"
        echo "${TD}" >> "${TMP_FILE}"
        echo "<a href=\"https://qa.debian.org/popcon-graph.php?packages=${PKG}&show_installed=on&want_legend=on&date_fmt=%25Y-%25m&beenhere=1\">q.d.o</a>" >> "${TMP_FILE}"
        echo "<a href=\"http://popcon2.net/package/${PKG}.html#graph-1\">p2.n</a>" >> "${TMP_FILE}"
        echo "<a href=\"http://lesbonscomptes.com/upopcon/makeimg.php?packages=${PKG}&columns=inst\">l.c/u</a>" >> "${TMP_FILE}"
        echo "</td>" >> "${TMP_FILE}"
        echo "</tr>" >> "${TMP_FILE}"
    done
    #
    echo "End ${PACKAGE}"
done

echo "</tbody>" >> "${TMP_FILE}"
echo "</table>" >> "${TMP_FILE}"
echo "</div>" >> "${TMP_FILE}"
echo "<br>" >> "${TMP_FILE}"


DEBIAN_DATE_TIME=$(date "+%Y-%m-%d %H:%M:%S" -r "${POPCON_DATA_DIR}/Debian/by_inst")
UBUNTU_DATE_TIME=$(date "+%Y-%m-%d %H:%M:%S" -r "${POPCON_DATA_DIR}/Ubuntu/by_inst")
echo "<b><a href=\"http://popcon.debian.org/\">Debian data</a> were updated:</b> ${DEBIAN_DATE_TIME}<br>" >> "${TMP_FILE}"
echo "<b><a href=\"http://popcon.ubuntu.com/\">Ubuntu data</a> were updated:</b> ${UBUNTU_DATE_TIME}<br>" >> "${TMP_FILE}"
echo "<br>" >> "${TMP_FILE}"
echo "<b>See also:</b>" >> "${TMP_FILE}"
echo "<a href=\"https://qa.debian.org/developer.php?login=Boris%20Pek\">qa.debian.org</a>" >> "${TMP_FILE}"
echo "<a href=\"./deb-packages.html\">deb-packages</a>" >> "${TMP_FILE}"
echo "<br>" >> "${TMP_FILE}"
echo "<br>" >> "${TMP_FILE}"
echo "</div>" >> "${TMP_FILE}"
echo "</div>" >> "${TMP_FILE}"

echo "<div id=\"footer\">" >> "${TMP_FILE}"
echo "Boris Pek &copy; ${PROJECT_YEARS}" >> "${TMP_FILE}"
echo "</div>" >> "${TMP_FILE}"

echo "</body>" >> "${TMP_FILE}"
echo "</html>" >> "${TMP_FILE}"
echo "" >> "${TMP_FILE}"
mv -f "${TMP_FILE}" "${HTML_FILE}"

if [ "${1}" = "open" ]; then
    xdg-open "${TMP_FILE}" &
fi

