#!/bin/sh

# Script to protect laptop from overheating.

CRIT_TEMP=98

while [ 1 ] ; do

    CUR_TEMP=`acpi -t | grep 'Thermal 3:' | awk '{ print $4 }'`
    CUR_TEMP_INT=`echo "${CUR_TEMP}" | sed -e "s/^\(.*\)\.[0-9]$/\1/"`

    if [ "${CUR_TEMP_INT}" -ge "${CRIT_TEMP}" ]; then
        # sensors && acpi -t
        echo "temp3: +${CUR_TEMP}°C (crit = +${CRIT_TEMP}°C)"

        TOP_STRING=`ps -eo comm=Command,pcpu --sort=-pcpu |
                    head -n 2 | tail -n 1 |
                    awk '{ print $1 " (" $2 "%)"}'`
        TOP_PROCESS=`echo "${TOP_STRING}" | sed -e "s/^\(.*\) (.*)$/\1/"`

        pkill -STOP "${TOP_PROCESS}"
        echo "Process ${TOP_STRING} was paused."
        sleep 1m;

        pkill -CONT "${TOP_PROCESS}"
        echo "Process ${TOP_PROCESS} was continued."
        sleep 1;
    else
        sleep 1;
    fi

done
