#!/bin/sh

# Test Internet connection:
host github.com > /dev/null || exit 1

export MAIN_DIR="$(dirname $(realpath -s ${0}))"

echo "MAIN_DIR = ${MAIN_DIR}"

for ARCHIVE in Debian Launchpad ; do
    cd "${MAIN_DIR}/${ARCHIVE}/"
    for PACKAGE in * ; do
        PKG_DIR="${MAIN_DIR}/${ARCHIVE}/${PACKAGE}/${PACKAGE}-debian"
        if [ ! -d "${PKG_DIR}" ]; then continue; fi
        if [ ! -e "${PKG_DIR}/.git" ]; then continue; fi

        echo;
        echo;
        echo "cd \"${PKG_DIR}\""
        cd "${PKG_DIR}"

        git push
        git push --tags
    done
done

