#!/bin/sh

export MAIN_DIR="$(dirname $(realpath -s ${0}))"

echo "MAIN_DIR = ${MAIN_DIR}"

echo
echo "cd ${MAIN_DIR}/Debian/"
cd "${MAIN_DIR}/Debian/"
for PACKAGE in * ; do
    [ "${PACKAGE}" = "libsignal-protocol-c" ] && continue

    PKG_DIR="${MAIN_DIR}/Debian/${PACKAGE}/${PACKAGE}-debian"
    [ ! -d "${PKG_DIR}" ] && continue
    [ ! -e "${PKG_DIR}/.git" ] && continue
    echo;
    echo "Begin ${PACKAGE}"
    cd "${PKG_DIR}"
    git checkout master
    git branch -a
    echo "End ${PACKAGE}"
done

echo
echo "cd ${MAIN_DIR}/Launchpad/"
cd "${MAIN_DIR}/Launchpad/"
for PACKAGE in * ; do
    PKG_DIR="${MAIN_DIR}/Launchpad/${PACKAGE}/${PACKAGE}-debian"
    [ ! -d "${PKG_DIR}" ] && continue
    [ ! -e "${PKG_DIR}/.git" ] && continue
    echo;
    echo "Begin ${PACKAGE}"
    cd "${PKG_DIR}"
    git checkout launchpad
    git branch -D master
    git branch -a
    echo "End ${PACKAGE}"
done

echo
echo "cd ${MAIN_DIR}/GitRepos/"
cd "${MAIN_DIR}/GitRepos/"
for SUBMODULE in * ; do
    SUBMODULE_DIR="${MAIN_DIR}/GitRepos/${SUBMODULE}"
    [ ! -d "${SUBMODULE_DIR}" ] && continue
    [ ! -e "${SUBMODULE_DIR}/.git" ] && continue
    echo;
    echo "Begin ${SUBMODULE}"
    cd "${SUBMODULE_DIR}"
    git checkout master
    git branch -a
    echo "End ${SUBMODULE}"
done

