#!/bin/sh

export MAIN_DIR="$(dirname $(realpath -s ${0}))"

echo "MAIN_DIR = ${MAIN_DIR}"

echo
echo "cd ${MAIN_DIR}/Debian/"
cd "${MAIN_DIR}/Debian/"
for PACKAGE in * ; do
    PKG_DIR="${MAIN_DIR}/Debian/${PACKAGE}/${PACKAGE}-debian"
    if [ ! -d "${PKG_DIR}" ]; then continue; fi
    if [ ! -e "${PKG_DIR}/.git" ]; then continue; fi
    echo;
    echo "Begin ${PACKAGE}"
    cd "${PKG_DIR}"
    git checkout master
    git branch -a
    echo "End ${PACKAGE}"
done

echo
echo "cd ${MAIN_DIR}/Launchpad/"
cd "${MAIN_DIR}/Launchpad/"
for PACKAGE in * ; do
    PKG_DIR="${MAIN_DIR}/Launchpad/${PACKAGE}/${PACKAGE}-debian"
    if [ ! -d "${PKG_DIR}" ]; then continue; fi
    if [ ! -e "${PKG_DIR}/.git" ]; then continue; fi
    echo;
    echo "Begin ${PACKAGE}"
    cd "${PKG_DIR}"
    git checkout launchpad
    git branch -D master
    git branch -a
    echo "End ${PACKAGE}"
done

