#!/bin/sh

export MAIN_DIR="${HOME}/WorkDir/Devel/deb_packages"

echo "MAIN_DIR = ${MAIN_DIR}"

cd "${MAIN_DIR}"/Debian/
for PACKAGE in * ; do
    PKG_DIR="${MAIN_DIR}/Debian/${PACKAGE}/${PACKAGE}-debian"
    if !([ -d "${PKG_DIR}" ]); then continue; fi
    echo;
    echo "Begin ${PACKAGE}"
    cd "${PKG_DIR}"
    git checkout master
    git pull --all
    git push origin master
    echo "End ${PACKAGE}"
done

cd "${MAIN_DIR}"/Launchpad/
for PACKAGE in * ; do
    PKG_DIR="${MAIN_DIR}/Launchpad/${PACKAGE}/${PACKAGE}-debian"
    if !([ -d "${PKG_DIR}" ]); then continue; fi
    echo;
    echo "Begin ${PACKAGE}"
    cd "${PKG_DIR}"
    git checkout launchpad
    git pull --all
    git push origin launchpad
    echo "End ${PACKAGE}"
done

