#!/bin/sh

export MAIN_DIR="${HOME}/WorkDir/Devel/deb_packages"

echo "MAIN_DIR = ${MAIN_DIR}"

cd "${MAIN_DIR}"/Debian/
for PACKAGE in * ; do
    echo;
    echo "Begin ${PACKAGE}"
    cd "${MAIN_DIR}/Debian/${PACKAGE}/${PACKAGE}-debian" || continue
    git checkout master
    git pull --all
    git push origin master
    echo "End ${PACKAGE}"
done

cd "${MAIN_DIR}"/Launchpad/
for PACKAGE in * ; do
    echo;
    echo "Begin ${PACKAGE}"
    cd "${MAIN_DIR}/Launchpad/${PACKAGE}/${PACKAGE}-debian" || continue
    git checkout launchpad
    git pull --all
    git push origin launchpad
    echo "End ${PACKAGE}"
done

