#!/bin/bash


if [ -z "${MAIN_DIR}" ]; then
    export MAIN_DIR="${PWD}/$(dirname ${0})/../.."
fi

export PACKAGE="elmerfem"

# Uncomment if necessary:
#export SFX="-3"

#export NEW_VER=6.1.0.svn.5396.dfsg2

# experimental unstable
export MAIN_DIST="unstable"


# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"


# Get old version
GetOldVersion
export OLD_COMMIT=$(echo ${OLD_VER} | sed -e "s/^.*.svn.\([0-9]\+\).dfsg.*$/\1/")


# Find new version
export CUR_VER="6.1.0"
if [ -z "${NEW_VER=}" ]; then
    export LAST_COMMIT=$(svn log https://elmerfem.svn.sourceforge.net/svnroot/elmerfem/trunk/ | head -n2 |grep "r[0-9]\+" | sed -e "s/^r\([0-9]\+\).*$/\1/")
    export NEW_VER="${CUR_VER}.svn.${LAST_COMMIT}.dfsg"
else
    export LAST_COMMIT=$(echo ${NEW_VER} | sed -e "s/^.*.svn.\([0-9]\+\).dfsg.*$/\1/")
fi
export NEW_VER_FULL=${NEW_VER}${SFX}


echo "https://elmerfem.svn.sourceforge.net/svnroot/elmerfem/trunk/"
echo ;
# Display versions
DisplayVersionsUnstable


# Print versions
PrintVersions "${@}"


# Check versions
#CheckVersionsUnstable


# Get the sources
if !([ -e "${PACKAGE}_${NEW_VER}.orig.tar.gz" ]); then
    "${PKG_DIR}/${PACKAGE}-debian/debian/elmerfem_get-orig-source.sh" "${NEW_VER}" | head -n 3
fi


export UPDATE_STRING="New upstream revision."

export A_TYPE="gz"
export D_ARGS="xzf"

export CLEAN_BUILD="true"

# Launch common script for updating packages and uploading them to mentors.debian.net
source "${MAIN_DIR}/Debian/updating_packages"

