#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="elmer-doc"

# Uncomment if necessary:
#export SFX="-2"

#export NEW_VER=2013.02.01
#export NEW_VER=2011.09.06

export A_TYPE="gz"


# experimental unstable
export MAIN_DIST="experimental"


# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"


# Get old version
GetOldVersion
export OLD_COMMIT=$(echo ${OLD_VER} | sed -e "s/^.*.svn.\([0-9]\+\).dfsg.*$/\1/")


# Get new version
if GetNewVersion "${@}"; then
    LAST_MOD=$(curl -I 'ftp://ftp.funet.fi/index/elmer/doc/ElmerDocumentation.tar.gz' 2>&1 | sed -ne "s/^.*Last-Modified: \(.*\) GMT.*$/\1/p")
    if [ -z "${LAST_MOD}" ]; then
        echo "Failed to define current version."
        exit 1
    fi
    NEW_VER=$(date -d "${LAST_MOD}" "+%Y.%m.%d")
fi
export NEW_VER_FULL=${NEW_VER}${SFX}


# Display versions
DisplayVersions "ftp://ftp.funet.fi/index/elmer/doc/"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get sources
GetSources


# Launch common script for updating of packages
source "${MAIN_DIR}/Debian/updating_packages"

