#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="qxmpp-qt4"

# Uncomment if necessary:
export SFX="-1ppa1"

#export NEW_VER=0.4.0~git20120405-390b63e

export A_TYPE="gz"


# Launch common script for setting variables
source "${MAIN_DIR}/Launchpad/setting_variables"
export MAIN_DIST="wily"
export UBUNTU_SFX="~${MAIN_DIST}1"


# Get old version
GetOldVersion


# Find new version
export DEVELOPER=qxmpp-project
export PROJECT=qxmpp
export VER_LIST=$(curl "https://github.com/${DEVELOPER}/${PROJECT}/tags" 2>&1 | sed -ne "s:^.*\"/${DEVELOPER}/${PROJECT}/archive/v\(.*\).tar.gz\" .*:\1:p")
if [ -z "${NEW_VER}" ]; then
    export NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
fi
export NEW_VER_FULL=${NEW_VER}${SFX}${UBUNTU_SFX}


# Display versions
DisplayVersions "https://github.com/${DEVELOPER}/${PROJECT}/tags"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get sources
GetSources
mv "qxmpp_${NEW_VER}.orig.tar.${A_TYPE}" "${PACKAGE}_${NEW_VER}.orig.tar.${A_TYPE}"


export UPDATE_STRING="Backport to Ubuntu Wily."

export DESTINATION="qxmpp"

export DIST_LIST="vivid
                  trusty"

export DIR_NAME="qxmpp-${NEW_VER}"
export OLD_DIR_NAME="qxmpp-${OLD_VER}"

# Launch common script for updating packages and uploading them to Launchpad
source "${MAIN_DIR}/Launchpad/updating_packages"

