#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="qxmpp"

export REMORE_BRANCH="alioth/launchpad"

source "${MAIN_DIR}/Debian/compare_with_package_on_Launchpad"
