#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="kde-gtk-config"

export EPOCH="3:"

# Uncomment if necessary:
export SFX="-1ppa1"


# Launch common script for setting variables
source "${MAIN_DIR}/Launchpad/setting_variables"


# Get old version
GetOldVersion


# Find new version
export PROJECT=kde-gtk-config
export VER_LIST=$(curl "http://download.kde.org/stable/plasma/" 2>&1 | sed -ne "s:^.*<td><a href=\"\([0-9].*\)/\">[0-9].*</a>.*$:\1:p")
export NEW_VER=$(echo "${VER_LIST}" | sort -V | tail -n1)
export NEW_VER_FULL=${NEW_VER}${SFX}${UBUNTU_SFX}


# Display versions
DisplayVersions "ftp://ftp.kde.org/pub/kde/stable/kde-gtk-config/"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get sources
GetSources


export EDIT_CHANGELOG="true"

export DESTINATION="kde-gtk-config"

export A_TYPE="xz"
export D_ARGS="xJf"

# Launch common script for updating packages and uploading them to Launchpad
source "${MAIN_DIR}/Launchpad/updating_packages"

