#!/bin/bash


if [ -z "${MAIN_DIR}" ]; then
    export MAIN_DIR="${PWD}/$(dirname ${0})/../.."
fi

export PACKAGE="kde-gtk-config"

# Uncomment if necessary:
#export SFX="-0ppa2"


# Launch common script for setting variables
source "${MAIN_DIR}/Launchpad/setting_variables"


# Get old version
GetOldVersion


# Find new version
export PROJECT=kde-gtk-config
#export VER_LIST=$(curl "http://proli.net/meu/netrunner/" 2>&1 | grep "kde-gtk-config" | grep ".tar.bz2" | sed -e "s:^.*href=\"kde-gtk-config-\(.*\).tar.bz2\">.*:\1:")
export VER_LIST=$(curl "ftp://ftp.kde.org/pub/kde/stable/kde-gtk-config/" 2>&1 | grep "drwxr-xr-x" | sed -e "s:^.* \(.*\)$:\1:")
export NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
export NEW_VER_FULL=${NEW_VER}${SFX}${UBUNTU_SFX}


# Display versions
DisplayVersions "ftp://ftp.kde.org/pub/kde/stable/kde-gtk-config/"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get the sources
if !([ -e "${PACKAGE}_${NEW_VER}.orig.tar.bz2" ]); then
    wget -4 -c "http://proli.net/meu/netrunner/${PROJECT}-${NEW_VER}.tar.bz2"
    mv -f "${PROJECT}-${NEW_VER}.tar.bz2" "${PACKAGE}_${NEW_VER}.orig.tar.bz2"
fi


export UPDATE_STRING="Update to stable release ${NEW_VER}."

export DESTINATION="kde-gtk-config"

export DIST_LIST="oneiric"

# Launch common script for updating packages and uploading them to Launchpad
source "${MAIN_DIR}/Launchpad/updating_packages"

