#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="psi"

# Uncomment if necessary:
#export SFX="-2"

export NEW_VER=1.5+dfsg1

export A_TYPE="xz"

# experimental unstable
export MAIN_DIST="unstable"


# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"


# Get old version
GetOldVersion


# Get new version
DEVELOPER=psi-im
PROJECT=psi
if GetNewVersion "${@}"; then
    # VER_LIST=$(curl 'https://sourceforge.net/projects/psi/files/Psi/' 2>&1 |sed -ne "s:^.*<tr title=\"\(.*\)\" class=\"folder \">.*$:\1:p")
    VER_LIST=$(curl "https://github.com/${DEVELOPER}/${PROJECT}/tags" 2>&1 | sed -ne "s:^.*\"/${DEVELOPER}/${PROJECT}/archive/refs/tags/\(.*\).tar.gz\" .*:\1:p")
    NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
fi
export NEW_VER_FULL=${NEW_VER}${SFX}


# Display versions
DisplayVersions "https://github.com/${DEVELOPER}/${PROJECT}/tags"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get sources
GetSourcesUsingUscan


export DIR_NAME="psi-1.5"

# Launch common script for updating of packages
source "${MAIN_DIR}/Debian/updating_packages"

