#!/bin/bash


export MAIN_DIR="${HOME}/WorkDir/Devel/deb_packages"

export PACKAGE="psi-plus-icons"

# Uncomment if necessary:
#export SFX="-2"

# experimental unstable
export MAIN_DIST="unstable"


# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"


# Check versions
export OLD_VER_FULL=$(head -n 1 "${PKG_DIR}/debian/changelog" | sed -e "s/.* (\(.*\)) .*/\1/")
export OLD_VER=$(echo ${OLD_VER_FULL} | sed -e "s/^\(.*\)-[0-9]$/\1/")
export OLD_SFX=$(echo ${OLD_VER_FULL} | sed -e "s/^.*\(-[0-9]\)$/\1/")

export VER_LIST=$(curl 'http://ppa.launchpad.net/psi-plus/ppa/ubuntu/pool/main/p/psi-plus-icons/' 2>&1 | grep 'psi-plus-icons_' | grep '.orig.tar.bz2' | sed -e "s/^.*psi-plus-icons_\(.*\).orig.tar.bz2.*$/\1/")
export NEW_VER=$(echo ${VER_LIST} | sed -e "s/^.* \(.*\)$/\1/")
export NEW_VER_FULL=${NEW_VER}${SFX}

echo " "
echo "http://ppa.launchpad.net/psi-plus/ppa/ubuntu/pool/main/p/psi-plus-icons/"
echo " "
echo "On Launchpad now available such versions:"
echo ${VER_LIST}
echo " "

echo "OLD_VER = ${OLD_VER}"
echo "NEW_VER = ${NEW_VER}"
echo "OLD_VER_FULL = ${OLD_VER_FULL}"
echo "NEW_VER_FULL = ${NEW_VER_FULL}"
echo " "

export UBUNTU_VER="${NEW_VER}"
export UBUNTU_SFX="-0ubuntu1"

if [ -z "${NEW_VER}" ]; then
    echo "NEW_VER is empty!";
    exit 0;
elif [ -z "${OLD_VER_FULL}" ]; then
    echo "OLD_VER_FULL is empty!";
    exit 0;
elif [ "${NEW_VER_FULL}" = "${OLD_VER_FULL}" ]; then
    echo "Upgrading is not required.";
    exit 0;
else
    if !([ "${NEW_VER}" = "${OLD_VER}" ]); then
        if !([ "${SFX}" = "-1" ]); then
            echo "Now SFX = ${SFX} but must be '-1' for a new release!";
            exit 0;
        fi
    else
        if ([ "${SFX}" = "-1" ]); then
            echo "Now SFX = ${SFX} but OLD_SFX = ${OLD_SFX}.";
            echo "Upgrading is not required.";
            exit 0;
        fi
    fi
fi


# Get the sources
if !([ -e "${PACKAGE}_${UBUNTU_VER}.orig.tar.bz2" ]); then
    wget -4 "http://ppa.launchpad.net/psi-plus/ppa/ubuntu/pool/main/p/psi-plus-icons/psi-plus-icons_${UBUNTU_VER}.orig.tar.bz2"
fi

if !([ -e "${PACKAGE}_${UBUNTU_VER}.orig.tar.bz2" ]); then
    echo "File ${PACKAGE}_${UBUNTU_VER}.orig.tar.bz2 is not found.";
    exit 0;
fi

if !([ -e "${PACKAGE}_${UBUNTU_VER}${UBUNTU_SFX}.debian.tar.gz" ]); then
    wget -4 "http://ppa.launchpad.net/psi-plus/ppa/ubuntu/pool/main/p/psi-plus-icons/psi-plus-icons_${UBUNTU_VER}${UBUNTU_SFX}.debian.tar.gz"
    rm -rf debian "${PACKAGE}-${UBUNTU_VER}"
    rm -rf "scripts__${PACKAGE}-${UBUNTU_VER}${UBUNTU_SFX}"
    rm -rf "debian__${PACKAGE}-${UBUNTU_VER}${UBUNTU_SFX}"
    tar xzf "${PACKAGE}_${UBUNTU_VER}${UBUNTU_SFX}.debian.tar.gz"
    mv -f debian/scripts "scripts__${PACKAGE}-${UBUNTU_VER}${UBUNTU_SFX}"
    mv -f debian "debian__${PACKAGE}-${UBUNTU_VER}${UBUNTU_SFX}"
fi

if !([ -e "${PACKAGE}_${UBUNTU_VER}${UBUNTU_SFX}.debian.tar.gz" ]); then
  echo "File ${PACKAGE}_${UBUNTU_VER}${UBUNTU_SFX}.debian.tar.gz is not found.";
  exit 0;
fi

export DEBIAN_DIFF="${PACKAGE}.debian.${UBUNTU_VER}${UBUNTU_SFX}.diff"
diff -ur "debian__${PACKAGE}-${UBUNTU_VER}${UBUNTU_SFX}" "${PKG_DIR}/debian" > "${DEBIAN_DIFF}"
kwrite "${DEBIAN_DIFF}"


export UPDATE_STRING="New upstream release"

# Launch common script for updating packages and uploading them to mentors.debian.net
source "${MAIN_DIR}/Debian/updating_packages"

