#!/bin/bash


############################# Some options ##############################################
export PACKAGE="psi-plus-icons"

# Uncomment if necessary:
#export SFX="-1"


############################# General part of script body ###############################
# experimental unstable
export MAIN_DIST="experimental"

if [ -z "${SFX}" ]; then
    export SFX="-1"
fi

export MAIN_DIR="${HOME}/WorkDir/Devel/deb_packages"

export PKG_DIR="${MAIN_DIR}/Debian/${PACKAGE}"
export TEMP_DIR="${PKG_DIR}/TEMP"
export TEST_DIR="${TEMP_DIR}/TEST"

mkdir -p "${TEMP_DIR}" && cd "${TEMP_DIR}"


############################# Specific part of script body ##############################
export OLD_VER_FULL=$(head -n 1 "${PKG_DIR}/debian/changelog" | sed -e "s/.* (\(.*\)) .*/\1/")
export OLD_VER=$(echo ${OLD_VER_FULL} | sed -e "s/^\(.*\)-[0-9]$/\1/")
export OLD_SFX=$(echo ${OLD_VER_FULL} | sed -e "s/^.*\(-[0-9]\)$/\1/")

export VER_LIST=$(curl 'http://ppa.launchpad.net/psi-plus/ppa/ubuntu/pool/main/p/psi-plus-icons/' 2>&1 | grep 'psi-plus-icons_' | grep '.orig.tar.bz2' | sed -e "s/^.*psi-plus-icons_\(.*\).orig.tar.bz2.*$/\1/")
export NEW_VER=$(echo ${VER_LIST} | sed -e "s/^.* \(.*\)$/\1/")
export NEW_VER_FULL=${NEW_VER}${SFX}

echo " "
echo "http://ppa.launchpad.net/psi-plus/ppa/ubuntu/pool/main/p/psi-plus-icons/"
echo " "
echo "On Launchpad now available such versions:"
echo ${VER_LIST}
echo " "

echo "OLD_VER = ${OLD_VER}"
echo "NEW_VER = ${NEW_VER}"
echo "OLD_VER_FULL = ${OLD_VER_FULL}"
echo "NEW_VER_FULL = ${NEW_VER_FULL}"
echo " "

export UBUNTU_VER="${NEW_VER}"
export UBUNTU_SFX="-0ubuntu1"

if [ -z "${NEW_VER}" ]; then
    echo "NEW_VER is empty!";
    exit 0;
elif [ -z "${OLD_VER_FULL}" ]; then
    echo "OLD_VER_FULL is empty!";
    exit 0;
elif [ "${NEW_VER_FULL}" = "${OLD_VER_FULL}" ]; then
    echo "Upgrading is not required.";
    exit 0;
else
    if !([ "${NEW_VER}" = "${OLD_VER}" ]); then
        if !([ "${SFX}" = "-1" ]); then
            echo "Now SFX = ${SFX} but must be '-1' for a new release!";
            exit 0;
        fi
    else
        if ([ "${SFX}" = "-1" ]); then
            echo "Now SFX = ${SFX} but OLD_SFX = ${OLD_SFX}.";
            echo "Upgrading is not required.";
            exit 0;
        fi
    fi
fi

if !([ -e "${PACKAGE}_${UBUNTU_VER}.orig.tar.bz2" ]); then
    wget -4 "http://ppa.launchpad.net/psi-plus/ppa/ubuntu/pool/main/p/psi-plus-icons/psi-plus-icons_${UBUNTU_VER}.orig.tar.bz2"
fi

if !([ -e "${PACKAGE}_${UBUNTU_VER}.orig.tar.bz2" ]); then
    echo "File ${PACKAGE}_${UBUNTU_VER}.orig.tar.bz2 is not found.";
    exit 0;
fi

if !([ -e "${PACKAGE}_${UBUNTU_VER}${UBUNTU_SFX}.debian.tar.gz" ]); then
    wget -4 "http://ppa.launchpad.net/psi-plus/ppa/ubuntu/pool/main/p/psi-plus-icons/psi-plus-icons_${UBUNTU_VER}${UBUNTU_SFX}.debian.tar.gz"
    rm -rf debian "${PACKAGE}-${UBUNTU_VER}"
    rm -rf "scripts__${PACKAGE}-${UBUNTU_VER}${UBUNTU_SFX}"
    rm -rf "debian__${PACKAGE}-${UBUNTU_VER}${UBUNTU_SFX}"
    tar xzf "${PACKAGE}_${UBUNTU_VER}${UBUNTU_SFX}.debian.tar.gz"
    mv -f debian/scripts "scripts__${PACKAGE}-${UBUNTU_VER}${UBUNTU_SFX}"
    mv -f debian "debian__${PACKAGE}-${UBUNTU_VER}${UBUNTU_SFX}"
fi

if !([ -e "${PACKAGE}_${UBUNTU_VER}${UBUNTU_SFX}.debian.tar.gz" ]); then
  echo "File ${PACKAGE}_${UBUNTU_VER}${UBUNTU_SFX}.debian.tar.gz is not found.";
  exit 0;
fi

export DEBIAN_DIFF="${PACKAGE}.debian.${UBUNTU_VER}${UBUNTU_SFX}.diff"
diff -ur "debian__${PACKAGE}-${UBUNTU_VER}${UBUNTU_SFX}" "${PKG_DIR}/debian" > "${DEBIAN_DIFF}"
kwrite "${DEBIAN_DIFF}"


############################# General part of script body ###############################
if !([ -e "${PACKAGE}_${UBUNTU_VER}.orig.tar.bz2" ]); then              # Specific code
    echo "File ${PACKAGE}_${UBUNTU_VER}.orig.tar.bz2 is not found.";    # Specific code
    exit 0;
fi


echo "Updating is started."

export DEBEMAIL="Boris Pek <tehnick-8@mail.ru>"

rm -rf "${PACKAGE}-${NEW_VER}" "${PACKAGE}_${NEW_VER}-"*

tar xjf "${PACKAGE}_${NEW_VER}.orig.tar.bz2"                            # Specific code
cp -rf "${PKG_DIR}/debian" "${PACKAGE}-${NEW_VER}/"

if ([ -d "${PACKAGE}-${OLD_VER}" ]); then
    diff -ur "${PACKAGE}-${OLD_VER}" "${PACKAGE}-${NEW_VER}" > \
             "${TEMP_DIR}/${PACKAGE}_${OLD_VER_FULL}:${NEW_VER_FULL}.diff"
fi

cd "${TEMP_DIR}/${PACKAGE}-${NEW_VER}"

echo " "
echo "Uscan:"
uscan --report-status
echo " "

export DIST="${MAIN_DIST}"
if [ "${SFX}" = "-1" ]; then
    dch -b --force-distribution --distribution "${DIST}" -v "${NEW_VER_FULL}" \
        "New upstream release"                                          # Specific code
    kwrite debian/changelog
    debuild -S -sa
else
    dch -b --force-distribution --distribution "${DIST}" -v "${NEW_VER_FULL}" \
        "Some fixes in package"                                         # Specific code
    kwrite debian/changelog
    # debuild -S -sd
    debuild -S -sa
fi


case "${1}" in
        fast)

    echo " "
    echo "Fast upload (without tests)."
    echo " "

        ;;
        *)

    echo " "
    echo "Now will be tests."
    echo " "

    rm -rf "${TEST_DIR}"
    mkdir -p "${TEST_DIR}" && cd "${TEST_DIR}"

    cp -r "${TEMP_DIR}/${PACKAGE}-${NEW_VER}" "${TEST_DIR}/"
    cp -f "${TEMP_DIR}/${PACKAGE}_${NEW_VER}.orig.tar.bz2" "${TEST_DIR}/"   # Specific code

    export BUILD_LOG_FILE="${TEMP_DIR}/${PACKAGE}-${NEW_VER_FULL}.build.log"
    cd "${TEST_DIR}/${PACKAGE}-${NEW_VER}"
    echo " "
    echo "Start building packages..."
    dpkg-buildpackage -rfakeroot > ${BUILD_LOG_FILE}
    echo "Finished building packages."
    echo " "

    export LINTIAN_LOG_FILE="${TEMP_DIR}/${PACKAGE}-${NEW_VER_FULL}.lintian.log"
    cd "${TEST_DIR}"
    echo " "
    echo "Now running lintian:"
    lintian -ivI ${PACKAGE}_${NEW_VER_FULL}_*.changes > ${LINTIAN_LOG_FILE}
    cat ${LINTIAN_LOG_FILE} | grep "E: "
    cat ${LINTIAN_LOG_FILE} | grep "W: "
    echo "Finished running lintian."
    echo " "
    kwrite ${LINTIAN_LOG_FILE}

    cd "${TEMP_DIR}/${PACKAGE}-${NEW_VER}"

        ;;
esac


kwrite debian/changelog


cd "${TEMP_DIR}"
cp -fr "${PACKAGE}-${NEW_VER}/debian" "${PKG_DIR}/"

dput -f mentors ${PACKAGE}_${NEW_VER_FULL}_source.changes

# Specific code
export DIFF_OUT="${PACKAGE}.debian.${NEW_VER_FULL}.out.diff"
diff -ur "debian__${PACKAGE}-${UBUNTU_VER}${UBUNTU_SFX}" "${PACKAGE}-${NEW_VER}/debian" > "${DIFF_OUT}"
# Specific code

echo "Update finished successfully"

