#!/bin/bash

if [ -z "${MAIN_DIR}" ]; then
    if [[ ${0} =~ ^/.+$ ]]; then
        export MAIN_DIR="$(dirname ${0})/../.."
    else
        export MAIN_DIR="${PWD}/$(dirname ${0})/../.."
    fi
fi

export PACKAGE="uhub"

# Uncomment if necessary:
#export SFX="-0ppa2"

#export NEW_VER=0.4.0~git20120423-9efe4bc


# Launch common script for setting variables
source "${MAIN_DIR}/Launchpad/setting_variables"


# Get old version
GetOldVersion


# Find new version
export DEVELOPER=janvidar
export PROJECT=uhub
export VER_LIST=$(curl "https://github.com/${DEVELOPER}/${PROJECT}/tags" 2>&1 | sed -ne "s:^.*\"/${DEVELOPER}/${PROJECT}/archive/\(.*\).tar.gz\" .*:\1:p")
if [ -z "${NEW_VER=}" ]; then
    export NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
fi
export NEW_VER_FULL=${NEW_VER}${SFX}${UBUNTU_SFX}


# Display versions
DisplayVersions "https://github.com/${DEVELOPER}/${PROJECT}/tags"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get the sources
if [ ! -e "${PACKAGE}_${NEW_VER}.orig.tar.xz" ]; then
    rm -rf  "${NEW_VER}" "${PACKAGE}-${NEW_VER}"
    # sources
    wget -4 -c "http://nodeload.github.com/${DEVELOPER}/${PROJECT}/tar.gz/${NEW_VER}"
    rm -rf ${PROJECT}-*
    tar xzf "${NEW_VER}"
    # tarball
    tar -cJf "${PACKAGE}_${NEW_VER}.orig.tar.xz" "${PACKAGE}-${NEW_VER}"
fi


export UPDATE_STRING="Update to stable release ${NEW_VER}."
export EDIT_CHANGELOG="true"

export A_TYPE="xz"
export D_ARGS="xJf"

export DIST_LIST="raring
                  quantal
                  precise"

# Launch common script for updating packages and uploading them to Launchpad
source "${MAIN_DIR}/Launchpad/updating_packages"

