.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH qgit 1 "2006-05-07"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
qgit \- QT interface to git trees, with stgit support.
.SH SYNOPSIS
.B qgit
.SH DESCRIPTION
QGit is a git GUI viewer built on Qt/C++. With QGit, you will be able to browse
git revisions history, view patch content and changed files, graphically follow
development branches.
.PP
QGit also offers some 
.IR stgit
integration, providing commands to move through the patch stack.
.SH OPTIONS
This program currently does not have any options.
.SH SEE ALSO
.BR git (7)
.br
The program is documented fully by
.IR "The QGit handbook",
available via the Help submenu.
.SH AUTHOR
QGit was written by Marco Costalba <mcostalba@users.sourceforge.net>
.PP
This manual page was written by Wartan Hachaturow <wart@debian.org>,
for the Debian project (but may be used by others).
