#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="elmerfem"

# Uncomment if necessary:
export SFX="-0ppa2"

#export NEW_VER=6.1.0.svn.5396.dfsg2

export A_TYPE="xz"

# Launch common script for setting variables
source "${MAIN_DIR}/Launchpad/setting_variables"


# Get old version
GetOldVersion
export OLD_COMMIT=$(echo ${OLD_VER} | sed -e "s/^.*.svn.\([0-9]\+\).dfsg.*$/\1/")


# Get new version
if GetNewVersion "${@}"; then
    DEVELOPER=ElmerCSC
    PROJECT=elmerfem
    VER_LIST=$(curl "https://github.com/${DEVELOPER}/${PROJECT}/tags" 2>&1 | sed -ne "s:^.*\"/${DEVELOPER}/${PROJECT}/archive/release-\(.*\).tar.gz\" .*:\1:p")
    NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
fi
export NEW_VER_FULL=${NEW_VER}${SFX}${UBUNTU_SFX}


echo "https://github.com/${DEVELOPER}/${PROJECT}/tags"
echo ;
# Display versions
DisplayVersionsUnstable


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersionsUnstable


# Get sources
GetSources


export UPDATE_STRING="New Git snapshot."

export DESTINATION="elmerfem"

export CLEAN_BUILD="true"

# Launch common script for updating of packages and uploading them to Launchpad
source "${MAIN_DIR}/Launchpad/updating_packages"

