#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="elmerfem"

export REMORE_BRANCH="alioth/master"

source "${MAIN_DIR}/Launchpad/compare_with_package_in_Debian"
