#!/bin/bash


if [ -z "${MAIN_DIR}" ]; then
    export MAIN_DIR="${PWD}/$(dirname ${0})/../.."
fi

export PACKAGE="q4wine"

# Uncomment if necessary:
#export SFX="-2ppa3"


# Launch common script for setting variables
source "${MAIN_DIR}/Launchpad/setting_variables"


# Get old version
GetOldVersion


# Find new version
export VER_LIST=$(curl 'http://sourceforge.net/projects/q4wine/files/q4wine/' 2>&1 | grep " class=\"folder warn\">" | grep "<tr title=\"q4wine " | sed -e "s:^.*<tr title=\"q4wine \(.*\)\" class=\"folder warn\">.*$:\1:")
export NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
export NEW_VER_FULL=${NEW_VER}${SFX}${UBUNTU_SFX}


# Display versions
DisplayVersions "http://sourceforge.net/projects/q4wine/files/q4wine/"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get the sources
if !([ -e "${PACKAGE}_${NEW_VER}.orig.tar.bz2" ]); then
    wget -4 -c "http://sourceforge.net/projects/q4wine/files/q4wine/q4wine%20${NEW_VER}/q4wine-${NEW_VER}.tar.bz2"
    mv -f "${PACKAGE}-${NEW_VER}.tar.bz2" "${PACKAGE}_${NEW_VER}.orig.tar.bz2"
fi


export UPDATE_STRING="Update to stable release ${NEW_VER}."

export DESTINATION="q4wine"

# Launch common script for updating packages and uploading them to Launchpad
source "${MAIN_DIR}/Launchpad/updating_packages"

