#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="ncdc"

# Uncomment if necessary:
export SFX="-3"

#export NEW_VER=1.22.1

export A_TYPE="gz"

# experimental unstable
export MAIN_DIST="unstable"


# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"


# Get old version
GetOldVersion


# Get new version
if GetNewVersion "${@}"; then
    VER_LIST=$(curl "https://dev.yorhel.nl/ncdc/changes" 2>&1 | sed -ne "s:^.*\"/download/ncdc-\(.*\).tar.gz\".*:\1:p")
    NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
fi
export NEW_VER_FULL=${NEW_VER}${SFX}


# Display versions
DisplayVersions "https://dev.yorhel.nl/ncdc/changes"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get sources
GetSourcesUsingUscan


# Launch common script for updating of packages
source "${MAIN_DIR}/Debian/updating_packages"

