#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export MAIN_DIST="wheezy-backports-sloppy"

export BPO_SFX="~bpo7+1"

#export BPO_VER=2.2.9-4

export BASIC_VER=2.2.9-3


source "$(dirname ${0})/backport_eiskaltdcpp"

