#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="plasma-widget-cwp"

# Uncomment if necessary:
# export SFX="-2"

# experimental unstable
export MAIN_DIST="unstable"


# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"


# Get old version
GetOldVersion


# Find new version
export VER_LIST=$(curl "http://kde-look.org/content/download.php?content=98925&id=1" 2>&1 | sed -ne "s:^.*/98925-cwp-\(.*\).tar.bz2.*:\1:p")
export NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
export NEW_VER_FULL=${NEW_VER}${SFX}


# Display versions
DisplayVersions "http://kde-look.org/content/show.php/?content=98925"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get sources
GetSources


export DIR_NAME="cwp-${NEW_VER}"
export OLD_DIR_NAME="cwp-${OLD_VER}"

export QT_SELECT=qt4

# Launch common script for updating packages and uploading them to mentors.debian.net
source "${MAIN_DIR}/Debian/updating_packages"

