#!/bin/bash


if [ -z "${MAIN_DIR}" ]; then
    if [[ ${0} =~ ^/.+$ ]]; then
        export MAIN_DIR="$(dirname ${0})/../.."
    else
        export MAIN_DIR="${PWD}/$(dirname ${0})/../.."
    fi
fi

export PACKAGE="plasma-widget-cwp"

# Uncomment if necessary:
export SFX="-2"

# experimental unstable
export MAIN_DIST="unstable"


# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"


# Get old version
GetOldVersion


# Find new version
export VER_LIST=$(curl "http://kde-look.org/content/download.php?content=98925&id=1" 2>&1 | sed -ne "s:^.*/98925-cwp-\(.*\).tar.bz2.*:\1:p")
export NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
export NEW_VER_FULL=${NEW_VER}${SFX}


# Display versions
DisplayVersions "http://kde-look.org/content/show.php/?content=98925"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get the sources
if [ ! -e "${PACKAGE}_${NEW_VER}.orig.tar.bz2" ]; then
    wget -4 -c "http://kde-look.org/CONTENT/content-files/98925-cwp-${NEW_VER}.tar.bz2"
    mv -f "98925-cwp-${NEW_VER}.tar.bz2" "${PACKAGE}_${NEW_VER}.orig.tar.bz2"
fi


export UPDATE_STRING="Update to stable release ${NEW_VER}."

export DIR_NAME="cwp-${NEW_VER}"
export OLD_DIR_NAME="cwp-${OLD_VER}"

export DM_FLAG="true"

# Launch common script for updating packages and uploading them to mentors.debian.net
source "${MAIN_DIR}/Debian/updating_packages"

