#!/bin/bash


if [ -z "${MAIN_DIR}" ]; then
    if [[ ${0} =~ ^/.+$ ]]; then
        export MAIN_DIR="$(dirname ${0})/../.."
    else
        export MAIN_DIR="${PWD}/$(dirname ${0})/../.."
    fi
fi

export PACKAGE="plasma-widget-cwp"

# Uncomment if necessary:
#export BPO_SFX="~bpo70+2"

#export BPO_VER=1.11.0-1

export BASIC_VER=1.10.2-1

# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"
source "${MAIN_DIR}/Debian/setting_variables_for_backports"


# Get old version
GetOldVersion


# Set versions
SetVersions


# Display versions
DisplayVersions


# Get the sources
if [ ! -e "${PACKAGE}_${PKG_VER}.orig.tar.bz2" ]; then
    dget -d http://ftp.de.debian.org/debian/pool/main/p/${PACKAGE}/${PACKAGE}_${PKG_VER_FULL}.dsc
fi


export DIR_NAME="cwp-${PKG_VER}"


# Launch common script for updating packages and uploading them to mentors.debian.net
source "${MAIN_DIR}/Debian/updating_packages_for_backports"

