#!/bin/sh

export NEW_VER="1.3.2"
export SFX="-1"


export DEBEMAIL="Boris Pek <tehnick-8@mail.ru>"

export MAIN_DIR="${HOME}/WorkDir/Devel/deb_packages/Debian/plasma-widget-cwp/"

cd "${MAIN_DIR}"
mkdir -p TEMP
cd ./TEMP

echo " "
echo "http://download.opensuse.org/repositories/home:/georg298/xUbuntu_10.04/"
echo " "
echo "On opensuse.org now available such versions:"
curl 'http://download.opensuse.org/repositories/home:/georg298/xUbuntu_10.04/' | grep 'kde-plasmoid-cwp_' | grep '.orig.tar.gz' | sed -e "s/^.*kde-plasmoid-cwp_\(.*\).orig.tar.gz.*$/\1/"
echo " "

export OLD_VER_FULL=$(head -n 1 ../debian/changelog | sed -e "s/.* (\(.*\)) .*/\1/")
export NEW_VER_FULL=${NEW_VER}${SFX}

echo "OLD_VER_FULL = ${OLD_VER_FULL}"
echo "NEW_VER_FULL = ${NEW_VER_FULL}"
echo " "

if [ -z "${OLD_VER_FULL}" ]; then
  echo "OLD_VER_FULL is empty!";
  exit 0;
elif [ "${NEW_VER_FULL}" = "${OLD_VER_FULL}" ]; then
  echo "Upgrading is not required.";
  exit 0;
fi

if !([ -e "kde-plasmoid-cwp_${NEW_VER}.orig.tar.gz" ]); then
  wget -4 "http://download.opensuse.org/repositories/home:/georg298/xUbuntu_10.04/kde-plasmoid-cwp_${NEW_VER}.orig.tar.gz"
fi

if !([ -e "kde-plasmoid-cwp_${NEW_VER}.orig.tar.gz" ]); then
  echo "File kde-plasmoid-cwp_${NEW_VER}.orig.tar.gz is not found.";
  exit 0;
fi

if ([ -e "plasma-widget-cwp_${NEW_VER_FULL}.debian.tar.gz" ]); then
  echo "File plasma-widget-cwp_${NEW_VER_FULL}.debian.tar.gz is found.";
  echo "Upgrading is not required.";
  exit 0;
fi

echo "Updating is started."

rm -r "plasma-widget-cwp-${NEW_VER}"
tar xzf "kde-plasmoid-cwp_${NEW_VER}.orig.tar.gz"
mv "cwp-${NEW_VER}" "plasma-widget-cwp-${NEW_VER}"
tar -czf "plasma-widget-cwp_${NEW_VER}.orig.tar.gz" "plasma-widget-cwp-${NEW_VER}"
cp -fr "../debian" "plasma-widget-cwp-${NEW_VER}/debian"


cd "plasma-widget-cwp-${NEW_VER}"
echo " "
echo "Uscan:"
uscan --report-status
echo " "
dch -b -v "${NEW_VER_FULL}" "Update to stable release ${NEW_VER}."
kwrite debian/changelog
debuild -S -sa
cd ..


case "${1}" in
        fast)

    echo " "
    echo "Fast upload (without tests)."
    echo " "

        ;;
        *)

    mkdir -p TEST
    rm -r ./TEST/*
    cp -r "plasma-widget-cwp-${NEW_VER}" ./TEST/
    cp -f "plasma-widget-cwp_${NEW_VER}.orig.tar.gz" ./TEST/

    cd ./TEST/"plasma-widget-cwp-${NEW_VER}"
    dpkg-buildpackage -rfakeroot
    cd ..

    export LINTIAN_LOG_FILE=../"plasma-widget-cwp-${NEW_VER_FULL}.lintian.log"
    echo " "
    echo "Now running lintian:"
    lintian -ivI plasma-widget-cwp_${NEW_VER_FULL}_i386.changes > ${LINTIAN_LOG_FILE}
    cat ${LINTIAN_LOG_FILE}
    echo "Finished running lintian."
    echo " "
    kwrite ${LINTIAN_LOG_FILE}
    cd ..

        ;;
esac


kwrite "plasma-widget-cwp-${NEW_VER}/debian/changelog"

dput -f mentors plasma-widget-cwp_${NEW_VER_FULL}_source.changes

cp -fr "plasma-widget-cwp-${NEW_VER}/debian" ../

echo "Update finished successfully"

