#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="kde-gtk-config"

export EPOCH="4:"

# Uncomment if necessary:
#export SFX="-3"

# export NEW_VER=5.10.4

export A_TYPE="xz"


# experimental unstable quantal
export MAIN_DIST="unstable"


# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"


# Get old version
GetOldVersion


# Get new version
if GetNewVersion "${@}"; then
    PROJECT=kde-gtk-config
    VER_LIST=$(curl "https://download.kde.org/stable/plasma/" 2>&1 | sed -ne "s:^.*<td><a href=\"\([0-9].*\)/\">[0-9].*</a>.*$:\1:p")
    NEW_VER=$(echo "${VER_LIST}" | sort -V | tail -n1)
fi
export NEW_VER_FULL=${NEW_VER}${SFX}


# Display versions
DisplayVersions "https://download.kde.org/stable/plasma/"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get sources
if [ ! -e "${PACKAGE}_${NEW_VER}.orig.tar.${A_TYPE}" ]; then
    set -e
    cd "${PKG_DIR}/${PACKAGE}-debian"
    uscan --download --verbose
    mv "${PKG_DIR}"/*.tar.${A_TYPE} "${TEMP_DIR}/"
    set +e
fi


# Launch common script for updating of packages
source "${MAIN_DIR}/Debian/updating_packages"

