#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="astromenace-data"

# Uncomment if necessary:
export SFX="-2"

export RPKGD="+repack"

export A_TYPE="xz"


# experimental unstable
export MAIN_DIST="unstable"

# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"


# Get old version
GetOldVersion

# Find new version
export VER_LIST=$(curl 'https://sourceforge.net/projects/openastromenace/files/' 2>&1 | sed -ne "s:^.*href=\"/projects/openastromenace/files/\(.*\)/\".*$:\1:p")
export CUR_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
export NEW_VER=${CUR_VER}${RPKGD}
export NEW_VER_FULL=${NEW_VER}${SFX}


# Display versions
DisplayVersions "https://sourceforge.net/projects/openastromenace/files/"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get sources
GetSources


export UPDATE_STRING="Update to stable release ${CUR_VER}."

#export DIR_NAME="AstroMenace"
#export OLD_DIR_NAME="AstroMenace"

# Launch common script for updating packages and uploading them to mentors.debian.net
source "${MAIN_DIR}/Debian/updating_packages"

