#!/bin/bash


if [ -z "${MAIN_DIR}" ]; then
    export MAIN_DIR="${PWD}/$(dirname ${0})/../.."
fi

export PACKAGE="astromenace"

# Uncomment if necessary:
#export SFX="-2"

export RPKGD="+ds"

# experimental unstable
export MAIN_DIST="experimental"

# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"


# Get old version
GetOldVersion

# Find new version
export VER_LIST=$(curl 'http://sourceforge.net/projects/openastromenace/files/' 2>&1 | sed -ne "s:^.*href=\"/projects/openastromenace/files/\(.*\)/\".*$:\1:p")
export CUR_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
export NEW_VER=${CUR_VER}${RPKGD}
export NEW_VER_FULL=${NEW_VER}${SFX}


# Display versions
DisplayVersions "http://sourceforge.net/projects/openastromenace/files/"


# Print versions
PrintVersions "${@}"


# Check versions
#CheckVersions


# Get the sources
if !([ -e "${PACKAGE}_${NEW_VER}.orig.tar.xz" ]); then
    wget -4 -c "http://sourceforge.net/projects/openastromenace/files/${CUR_VER}/astromenace-src-${CUR_VER}.tar.bz2"
    tar xjf "astromenace-src-${CUR_VER}.tar.bz2"
    rm -r "AstroMenace/RAW_VFS_DATA/FONT" "AstroMenace/AstroMenaceSource"
    rm "AstroMenace/MacOSX.zip" "AstroMenace/CMakeLists.txt" "AstroMenace/CodeBlocks.cbp"
    tar -cJf "astromenace-data_${NEW_VER}.orig.tar.xz" "AstroMenace"
fi


export UPDATE_STRING="Update to stable release ${NEW_VER}."

export A_TYPE="xz"
export D_ARGS="xJf"

export DIR_NAME="AstroMenace"
export OLD_DIR_NAME="AstroMenace"

# Launch common script for updating packages and uploading them to mentors.debian.net
source "${MAIN_DIR}/Debian/updating_packages"

