#!/bin/bash

set -e

export PKG_DIR="${MAIN_DIR}/Debian/${PACKAGE}"
export TEMP_DIR="${PKG_DIR}/TEMP"

if [ -z "${REMOTE_BRANCH}" ]; then
    export REMOTE_BRANCH="origin/launchpad"
fi

if [ -z "${TEST_DIR}" ]; then
    export TEST_DIR="debian"
fi

cd "${PKG_DIR}/${PACKAGE}-debian"
git diff "${REMOTE_BRANCH}" "${TEST_DIR}" > "${TEMP_DIR}/debian.diff"
kwrite "${TEMP_DIR}/debian.diff" &> /dev/null &

