#!/bin/bash
#
# Common script for setting variables for backports

if [ -z "${MAIN_DIST}" ]; then
    # jessie-backports-sloppy stretch-backports
    export MAIN_DIST="stretch-backports"
fi

if [ -z "${BPO_SFX}" ]; then
    export BPO_SFX="~bpo9+1"
fi


export TEMP_DIR="${PKG_DIR}/TEMP/BACKPORT-${MAIN_DIST}"
export TEST_DIR="${TEMP_DIR}/TEST"

cd "${PKG_DIR}/${PACKAGE}-debian" || exit 1

mkdir -p "${TEMP_DIR}"
cd "${TEMP_DIR}" || exit 1

export UPDATE_STRING="Rebuild for ${MAIN_DIST}."
export BPO_BASEPATH="/opt/pbuilder/${MAIN_DIST}"


# Set versions
SetVersions()
{
    export PKG_VER=${OLD_VER}
    if [ -z "${BASIC_VER}" ]; then
        # BASIC_VER --- current package version in backports or in stable.
        # It is used to fill in change log in binary packages for backports.
        export BASIC_VER=${PKG_VER}
    fi
    export PKG_VER_FULL=${OLD_VER_FULL}
    if [ -z "${BPO_VER}" ]; then
        export BPO_VER=${PKG_VER_FULL}
    fi
    export BPO_VER_FULL=${BPO_VER}${BPO_SFX}
}

# Display versions
DisplayVersions()
{
    echo "PKG_VER = ${PKG_VER}"
    echo "BPO_VER = ${BPO_VER}"
    echo "PKG_VER_FULL = ${EPOCH}${PKG_VER_FULL}"
    echo "BPO_VER_FULL = ${EPOCH}${BPO_VER_FULL}"
    echo ;
}

# Get source package
GetSourcePackage()
{
    if [ ! -e "${PACKAGE}_${PKG_VER}.orig.tar.${A_TYPE}" ]; then
        if [ "${PACKAGE:0:3}" = "lib" ]; then
            dget -d "https://deb.debian.org/debian/pool/main/${PACKAGE:0:4}/${PACKAGE}/${PACKAGE}_${PKG_VER_FULL}.dsc"
        else
            dget -d "https://deb.debian.org/debian/pool/main/${PACKAGE:0:1}/${PACKAGE}/${PACKAGE}_${PKG_VER_FULL}.dsc"
        fi
    fi
}

