#!/bin/bash

# Common script for setting variables

export TEMP_DIR="${PKG_DIR}/TEMP/BACKPORT"
export TEST_DIR="${TEMP_DIR}/TEST"

cd "${PKG_DIR}/${PACKAGE}-debian" || exit 1

mkdir -p "${TEMP_DIR}"
cd "${TEMP_DIR}" || exit 1

# wheezy-backports-sloppy jessie-backports
export MAIN_DIST="jessie-backports"

if [ -z "${BPO_SFX}" ]; then
    export BPO_SFX="~bpo8+1"
fi

export UPDATE_STRING="Rebuild for ${MAIN_DIST}."
export BPO_BASEPATH="${HOME}/WorkDir/Devel/pbuilder/${MAIN_DIST}"


# Set versions
SetVersions()
{
    export PKG_VER=${OLD_VER}
    if [ -z "${BASIC_VER}" ]; then
        # BASIC_VER --- current package version in backports or in stable.
        # It is used to fill in change log in binary packages for backports.
        export BASIC_VER=${PKG_VER}
    fi
    export PKG_VER_FULL=${OLD_VER_FULL}
    if [ -z "${BPO_VER}" ]; then
        export BPO_VER=${PKG_VER_FULL}
    fi
    export BPO_VER_FULL=${BPO_VER}${BPO_SFX}
}

# Display versions
DisplayVersions()
{
    echo "PKG_VER = ${PKG_VER}"
    echo "BPO_VER = ${BPO_VER}"
    echo "PKG_VER_FULL = ${EPOCH}${PKG_VER_FULL}"
    echo "BPO_VER_FULL = ${EPOCH}${BPO_VER_FULL}"
    echo ;
}

# Get source package
GetSourcePackage()
{
    if [ ! -e "${PACKAGE}_${PKG_VER}.orig.tar.${A_TYPE}" ]; then
        dget -d http://httpredir.debian.org/debian/pool/main/${PACKAGE:0:1}/${PACKAGE}/${PACKAGE}_${PKG_VER_FULL}.dsc
    fi
}

