#!/bin/bash
#
# Common script for setting variables

export PKG_DIR="${MAIN_DIR}/Debian/${PACKAGE}"

[ -z "${SFX}" ] && export SFX="-1"

source "${MAIN_DIR}/Tools/common_variables.sh" || exit 1
source "${MAIN_DIR}/Tools/common_functions.sh" || exit 1

