#!/bin/bash
#
# Common script for updating packages


CheckBasicVariables || exit 1
CheckTarballAvailability || exit 1
DefineTarOptions || exit 1
DefineAdditionalVariables

ReportStartOfUpdate
PrepareSourcePackage
PrepareDiff
CheckAvailableVersions
UpdateSourcePackage
DoMainChecks

OpenChangeLog
CopyUpdatedChangelogToGit
ReportBuildSuccess
ShowPromptForPackageUpload
OpenTerminal
UpdateLocalRepo

