#!/bin/bash

# This is the common script for updating packages and uploading them to mentors.debian.net
#
# It make such actions:
# 1) Update changelog.
# 2) Prepare sources to upload.
#    Build the package and check it using lintian (optional)
# 3) Upload sources to mentors.debian.net


if [ -z "${PACKAGE}" ]; then
    echo "Error: PACKAGE variable is empty!";
    exit 1;
elif [ -z "${NEW_VER}" ]; then
    echo "Error: NEW_VER variable is empty!";
    exit 1;
fi

if [ -z "${A_TYPE}" ]; then
    export A_TYPE="bz2"
    export D_ARGS="xjf"
fi

if [ ! -e "${PACKAGE}_${NEW_VER}.tar.${A_TYPE}" ]; then
    echo "File ${PACKAGE}_${NEW_VER}.tar.${A_TYPE} is not found.";
    exit 0;
fi

if [ "${1}" = "clean" ]; then
    export CLEAN_BUILD="true"
fi

export DIR_NAME="${PACKAGE}-${NEW_VER}"
export OLD_DIR_NAME="${PACKAGE}-${OLD_VER}"


echo "Updating is started."

export DEBEMAIL="Boris Pek <tehnick@debian.org>"

rm -rf "${PACKAGE}_${NEW_VER}.tar.${A_TYPE}"

if ([ -d "${OLD_DIR_NAME}" ]); then
    diff -urN "${OLD_DIR_NAME}" "${DIR_NAME}" > \
              "${TEMP_DIR}/${OLD_VER_FULL}::${NEW_VER_FULL}.diff"
fi

cd "${TEMP_DIR}/${DIR_NAME}"

export DIST="${MAIN_DIST}"
dch -b --force-distribution --distribution "${DIST}" -v "${EPOCH}${NEW_VER_FULL}" \
    "${UPDATE_STRING}"
kwrite debian/changelog
nice -n19 debuild -S -sa


if [ "${1}" = "fast" ]; then
    echo ;
    echo "Fast upload (without tests)."
    echo ;
else
    echo ;
    echo "Now will be tests."
    echo ;

    if [ "${CLEAN_BUILD}" = "true" ]; then
        sudo rm -rf "${TEST_DIR}"/*
    else
        rm -rf "${TEST_DIR}"/*
    fi

    mkdir -p "${TEST_DIR}"
    cd "${TEST_DIR}" || exit 1

    cp -r "${TEMP_DIR}/${DIR_NAME}" "${TEST_DIR}/"
    cp -f "${TEMP_DIR}/${PACKAGE}_${NEW_VER}.tar.${A_TYPE}" "${TEST_DIR}/"

    export BUILD_LOG_FILE="${TEMP_DIR}/${PACKAGE}-${NEW_VER_FULL}.build.log"
    export WARNINGS_LOG_FILE="${TEMP_DIR}/${PACKAGE}-${NEW_VER_FULL}.warnings.log"
    cd "${TEST_DIR}/${DIR_NAME}"
    echo ;
    echo "Start building packages..."
    if [ "${CLEAN_BUILD}" = "true" ]; then
        sudo time nice -n19 pdebuild --pbuilder cowbuilder \
                                     --buildresult "${TEST_DIR}" > \
                                     ${BUILD_LOG_FILE} \
                                     2> ${WARNINGS_LOG_FILE} || exit 1
        sudo chown -R "${SUDO_USER}:${SUDO_USER}" "${TEST_DIR}"
    else
        time nice -n19 dpkg-buildpackage -rfakeroot > ${BUILD_LOG_FILE} 2> ${WARNINGS_LOG_FILE} || exit 1
    fi
    cat  ${WARNINGS_LOG_FILE}
    echo "Finished building packages."
    echo ;

    export LINTIAN_LOG_FILE="${TEMP_DIR}/${PACKAGE}-${NEW_VER_FULL}.lintian.log"
    cd "${TEST_DIR}"
    echo ;
    echo "Now running lintian:"
    time nice -n19 lintian -ivIE --pedantic ${PACKAGE}_${NEW_VER_FULL}_*.changes > ${LINTIAN_LOG_FILE}
    grep "E: " "${LINTIAN_LOG_FILE}"
    grep "W: " "${LINTIAN_LOG_FILE}"
    grep "I: " "${LINTIAN_LOG_FILE}"
    grep "P: " "${LINTIAN_LOG_FILE}"
    grep "X: " "${LINTIAN_LOG_FILE}"
    echo "Finished running lintian."
    echo ;
    kwrite ${LINTIAN_LOG_FILE}

    cd "${TEMP_DIR}/${DIR_NAME}"
fi


kwrite debian/changelog


cd "${TEMP_DIR}"
cp -fr "${DIR_NAME}/debian" "${PKG_DIR}/${PACKAGE}-debian/"


echo "Update finished successfully"


if [ "${2}" = "new" ]; then
    cd "${TEST_DIR}"
    debsign "${PACKAGE}_${NEW_VER_FULL}_i386.changes"
    echo "Package is targeted into NEW queue, so binary upload is required:"
    echo "dput -f ftp-eu ${PACKAGE}_${NEW_VER_FULL}_i386.changes"
else
    cd "${TEMP_DIR}"
    echo "Sorce-only upload:"
    echo "dput -f ftp-eu ${PACKAGE}_${NEW_VER_FULL}_source.changes"
fi


konsole &> /dev/null &


# Local repo
if [ "${1}" != "fast" ]; then
    export APT_DIR="${MAIN_DIR}/LocalRepo"
    mkdir -p "${APT_DIR}/${PACKAGE}/"
    cp -f "${TEST_DIR}"/*.deb "${APT_DIR}/${PACKAGE}/"
    cd "${APT_DIR}/" || exit 1
    rm -f Packages* InRelease* Release*
    apt-ftparchive packages . > Packages
    gzip -c Packages > Packages.gz
    gpg -abs -o Packages.gpg Packages.gz
fi

