#!/bin/bash
#
# Common script for updating packages for backports

if [ -z "${PACKAGE}" ]; then
    echo "Error: PACKAGE variable is empty!";
    exit 1;
fi

case "${A_TYPE}" in
"gz")
    export D_ARGS="xzf"
;;
"bz2")
    export D_ARGS="xjf"
;;
"xz")
    export D_ARGS="xJf"
;;
*)
    echo "Tarball type is not defined!"
    exit 1
;;
esac

if [ ! -e "${PACKAGE}_${PKG_VER}.orig.tar.${A_TYPE}" ]; then
    echo "File ${PACKAGE}_${PKG_VER}.orig.tar.${A_TYPE} is not found.";
    exit 0;
fi

if [ -z "${DIR_NAME}" ]; then
    export DIR_NAME="${PACKAGE}-${PKG_VER}"
fi

if [ "${1}" = "fast" ]; then
    export FAST_UPLOAD="true"
elif [ "${1}" = "new" ]; then
    export TARGETED_TO_NEW_QUEUE="true"
fi

echo "Updating is started."


rm -rf "${DIR_NAME}" "${PACKAGE}_${PKG_VER}-"*

tar "${D_ARGS}" "${PACKAGE}_${PKG_VER}.orig.tar.${A_TYPE}"
rm -rf "${DIR_NAME}/debian"
cp -rf "${PKG_DIR}/${PACKAGE}-debian/debian" "${DIR_NAME}/debian"

cd "${TEMP_DIR}/${DIR_NAME}"

{
    # About --buildinfo-option="-O" see at: https://bugs.debian.org/853795#10
    dch -b --force-distribution --distribution "${MAIN_DIST}" -v "${EPOCH}${BPO_VER_FULL}" \
        "${UPDATE_STRING}"
    kwrite debian/changelog
    debuild -S -sa -d --buildinfo-option="-O" "-v${BASIC_VER}" || exit 1
}


if [ "${FAST_UPLOAD}" = "true" ]; then
    echo ;
    echo "Fast upload (without tests)."
    echo ;
else
    echo ;
    echo "Now will be tests."
    echo ;

    sudo rm -rf "${TEST_DIR}"/*
    mkdir -p "${TEST_DIR}"
    cd "${TEST_DIR}" || exit 1

    cp -r "${TEMP_DIR}/${DIR_NAME}" "${TEST_DIR}/"
    cp -f "${TEMP_DIR}/${PACKAGE}_${PKG_VER}.orig.tar.${A_TYPE}" "${TEST_DIR}/"
    cp -f "${TEMP_DIR}/${PACKAGE}_${BPO_VER_FULL}.debian.tar."* "${TEST_DIR}/"
    cp -f "${TEMP_DIR}/${PACKAGE}_${BPO_VER_FULL}.dsc" "${TEST_DIR}/"
    
    export BUILD_LOG_FILE="${TEMP_DIR}/__${PACKAGE}-${BPO_VER_FULL}.build.log"
    export WARNINGS_LOG_FILE="${TEMP_DIR}/__${PACKAGE}-${BPO_VER_FULL}.warnings.log"
    echo ;

    cd "${TEST_DIR}/${DIR_NAME}"
    echo "Start building packages..."
    sudo time nice -n19 pdebuild --pbuilder cowbuilder \
                                 --buildresult "${TEST_DIR}" -- \
                                 --basepath "${BPO_BASEPATH}" \
                                 --debbuildopts "-v${BASIC_VER}" \
                                 > ${BUILD_LOG_FILE} \
                                 2> ${WARNINGS_LOG_FILE} || exit 1
    sudo chown -R "${SUDO_USER}:${SUDO_USER}" "${TEST_DIR}"
    cat  ${WARNINGS_LOG_FILE}
    echo "Finished building packages."
    echo ;

    export LINTIAN_LOG_FILE="${TEMP_DIR}/__${PACKAGE}-${BPO_VER_FULL}.lintian.log"
    cd "${TEST_DIR}"
    echo ;
    echo "Now running lintian:"
    time nice -n19 lintian -ivIE --pedantic ${PACKAGE}_${BPO_VER_FULL}_*.changes > ${LINTIAN_LOG_FILE}
    grep "E: " "${LINTIAN_LOG_FILE}"
    grep "W: " "${LINTIAN_LOG_FILE}"
    grep "I: " "${LINTIAN_LOG_FILE}"
    grep "P: " "${LINTIAN_LOG_FILE}"
    grep "X: " "${LINTIAN_LOG_FILE}"
    echo "Finished running lintian."
    echo ;
    kwrite ${LINTIAN_LOG_FILE}

    cd "${TEMP_DIR}/${DIR_NAME}"
fi


cd "${TEMP_DIR}"
cp -fr "${DIR_NAME}/debian" "${PKG_DIR}/${PACKAGE}-debian/"


echo "Update finished successfully"


if [ "${TARGETED_TO_NEW_QUEUE}" = "true" ]; then
    cd "${TEST_DIR}"
    ARCHITECTURE="$(dpkg --print-architecture)"
    debsign "${PACKAGE}_${BPO_VER_FULL}_${ARCHITECTURE}.changes"
    echo ;
    echo "Package is targeted into NEW queue, so binary upload is required:"
    echo "dput -f ftp-eu ${PACKAGE}_${BPO_VER_FULL}_${ARCHITECTURE}.changes"
else
    cd "${TEMP_DIR}"
    echo "Sorce-only upload:"
    echo "dput -f ftp-eu ${PACKAGE}_${BPO_VER_FULL}_source.changes"
fi


konsole &> /dev/null &

