#!/bin/bash


if [ -z "${MAIN_DIR}" ]; then
    if [[ ${0} =~ ^/.+$ ]]; then
        export MAIN_DIR="$(dirname ${0})/../.."
    else
        export MAIN_DIR="${PWD}/$(dirname ${0})/../.."
    fi
fi

export PACKAGE="plasma-widget-cwp"

# Uncomment if necessary:
#export SFX="-1ppa1"


# Launch common script for setting variables
source "${MAIN_DIR}/Launchpad/setting_variables"


# Get old version
GetOldVersion


# Find new version
export VER_LIST=$(curl "http://kde-look.org/content/download.php?content=98925&id=1" 2>&1 | sed -ne "s:^.*/98925-cwp-\(.*\).tar.bz2.*:\1:p")
export NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
export NEW_VER_FULL=${NEW_VER}${SFX}${UBUNTU_SFX}


# Display versions
DisplayVersions "http://kde-look.org/content/show.php/?content=98925"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get the sources
if [ ! -e "${PACKAGE}_${NEW_VER}.orig.tar.bz2" ]; then
    "${PKG_DIR}/${PACKAGE}-debian/debian/rules" "get-orig-source"
fi


export UPDATE_STRING="Update to stable release ${NEW_VER}."

export DESTINATION="plasma-widget-cwp"

export DIR_NAME="cwp-${NEW_VER}"
export OLD_DIR_NAME="cwp-${OLD_VER}"

# Launch common script for updating packages and uploading them to Launchpad
source "${MAIN_DIR}/Launchpad/updating_packages"

