#!/bin/sh

export NEW_VER="1.3.1"
export PR="-1ppa1"


export DEBEMAIL="Boris Pek <tehnick-8@mail.ru>"

cd "${HOME}/WorkDir/Devel/CWP/Launchpad/"

# apt-get source plasma-widget-cwp

if !([ -e plasma-widget-cwp_${NEW_VER}.orig.tar.gz ]); then
  echo "File plasma-widget-cwp_${NEW_VER}.orig.tar.gz is not found.";
  exit 0;
fi

echo "Updating is started."

rm plasma-widget-cwp_${NEW_VER}-*

cd "plasma-widget-cwp-${NEW_VER}"

# begin update for basic releases
dch -b --force-distribution --distribution "natty" -v "${NEW_VER}${PR}~natty1" \
  "Update to stable release ${NEW_VER}."
## "Update to stable release ${NEW_VER}."
## "Some fixes in deb package."
kwrite debian/changelog
debuild -S -sa
# end update for basic releases

# Full list: hardy intrepid jaunty karmic lucid maverick natty
# But not all of them are available, see: https://launchpad.net/ubuntu/+ppas
# begin update for other releases
cp debian/changelog ../changelog # copy basic changelog

cp -f ../changelog debian/changelog
dch -b --force-distribution --distribution "maverick" -v "${NEW_VER}${PR}~maverick1" \
  "Automated backport upload; no source changes."
debuild -S -sd

cp -f ../changelog debian/changelog
dch -b --force-distribution --distribution "lucid" -v "${NEW_VER}${PR}~lucid1" \
  "Automated backport upload; no source changes."
debuild -S -sd

cp -f ../changelog debian/changelog
dch -b --force-distribution --distribution "karmic" -v "${NEW_VER}${PR}~karmic1" \
  "Automated backport upload; no source changes."
debuild -S -sd

mv debian/source ../ # make dirty hack

cp -f ../changelog debian/changelog
dch -b --force-distribution --distribution "jaunty" -v "${NEW_VER}${PR}~jaunty1" \
  "Automated backport upload; no source changes."
debuild -S -sd

mv ../source debian/ # rollback dirty hack

mv ../changelog debian/changelog # rollback basic changelog
# end update for other releases

kwrite debian/changelog

cd ..
dput -f ubuntu plasma-widget-cwp_${NEW_VER}${PR}~natty1_source.changes
dput -f ubuntu plasma-widget-cwp_${NEW_VER}${PR}~maverick1_source.changes
dput -f ubuntu plasma-widget-cwp_${NEW_VER}${PR}~lucid1_source.changes
dput -f ubuntu plasma-widget-cwp_${NEW_VER}${PR}~karmic1_source.changes
dput -f ubuntu plasma-widget-cwp_${NEW_VER}${PR}~jaunty1_source.changes

echo "Update finished successfully"

