#!/bin/sh

export NEW_VER="1.3.2"
export SFX="-1ppa1"
export UBUNTU_SFX="~natty1"

export DEBEMAIL="Boris Pek <tehnick-8@mail.ru>"

export MAIN_DIR="${HOME}/WorkDir/Devel/deb_packages/Launchpad/plasma-widget-cwp/"

cd "${MAIN_DIR}"
mkdir -p TEMP
cd ./TEMP

echo " "
echo "http://download.opensuse.org/repositories/home:/georg298/xUbuntu_10.04/"
echo " "
echo "On opensuse.org now available such versions:"
curl 'http://download.opensuse.org/repositories/home:/georg298/xUbuntu_10.04/' | grep 'kde-plasmoid-cwp_' | grep '.orig.tar.gz' | sed -e "s/^.*kde-plasmoid-cwp_\(.*\).orig.tar.gz.*$/\1/"
echo " "

export OLD_VER_FULL=$(head -n 1 ../debian/changelog | sed -e "s/.* (\(.*\)) .*/\1/")
export NEW_VER_FULL=${NEW_VER}${SFX}${UBUNTU_SFX}

echo "OLD_VER_FULL = ${OLD_VER_FULL}"
echo "NEW_VER_FULL = ${NEW_VER_FULL}"
echo " "

if [ -z "${OLD_VER_FULL}" ]; then
  echo "OLD_VER_FULL is empty!";
  exit 0;
elif [ "${NEW_VER_FULL}" = "${OLD_VER_FULL}" ]; then
  echo "Upgrading is not required.";
  exit 0;
fi

if !([ -e "kde-plasmoid-cwp_${NEW_VER}.orig.tar.gz" ]); then
  wget -4 "http://download.opensuse.org/repositories/home:/georg298/xUbuntu_10.04/kde-plasmoid-cwp_${NEW_VER}.orig.tar.gz"
fi

if !([ -e "kde-plasmoid-cwp_${NEW_VER}.orig.tar.gz" ]); then
  echo "File kde-plasmoid-cwp_${NEW_VER}.orig.tar.gz is not found.";
  exit 0;
fi

if ([ -e "plasma-widget-cwp_${NEW_VER_FULL}.debian.tar.gz" ]); then
  echo "File plasma-widget-cwp_${NEW_VER_FULL}.debian.tar.gz is found.";
  echo "Upgrading is not required.";
  exit 0;
fi

echo "Updating is started."

rm -r "plasma-widget-cwp-${NEW_VER}"
tar xzf "kde-plasmoid-cwp_${NEW_VER}.orig.tar.gz"
mv "cwp-${NEW_VER}" "plasma-widget-cwp-${NEW_VER}"
tar -czf "plasma-widget-cwp_${NEW_VER}.orig.tar.gz" "plasma-widget-cwp-${NEW_VER}"
cp -fr "../debian" "plasma-widget-cwp-${NEW_VER}/debian"

rm -f plasma-widget-cwp_${NEW_VER}-*

cd "plasma-widget-cwp-${NEW_VER}"

# begin update for basic releases
dch -b --force-distribution --distribution "natty" -v "${NEW_VER}${SFX}${UBUNTU_SFX}" \
  "Update to stable release ${NEW_VER}."
## "Update to stable release ${NEW_VER}."
## "Some fixes in deb package."
kwrite debian/changelog
debuild -S -sa
# end update for basic releases

# Full list: hardy intrepid jaunty karmic lucid maverick natty
# But not all of them are available, see: https://launchpad.net/ubuntu/+ppas
# begin update for other releases
cp debian/changelog ../changelog # copy basic changelog

cp -f ../changelog debian/changelog
dch -b --force-distribution --distribution "maverick" -v "${NEW_VER}${SFX}~maverick1" \
  "Automated backport upload; no source changes."
debuild -S -sd

cp -f ../changelog debian/changelog
dch -b --force-distribution --distribution "lucid" -v "${NEW_VER}${SFX}~lucid1" \
  "Automated backport upload; no source changes."
debuild -S -sd

cp -f ../changelog debian/changelog
dch -b --force-distribution --distribution "karmic" -v "${NEW_VER}${SFX}~karmic1" \
  "Automated backport upload; no source changes."
debuild -S -sd

mv debian/source ../ # make dirty hack

cp -f ../changelog debian/changelog
dch -b --force-distribution --distribution "jaunty" -v "${NEW_VER}${SFX}~jaunty1" \
  "Automated backport upload; no source changes."
debuild -S -sd

mv ../source debian/ # rollback dirty hack

mv ../changelog debian/changelog # rollback basic changelog
# end update for other releases

cd ..


case "${1}" in
        fast)

    echo " "
    echo "Fast upload (without tests)."
    echo " "

        ;;
        *)

    mkdir -p TEST
    rm -r ./TEST/*
    cp -r "plasma-widget-cwp-${NEW_VER}" ./TEST/
    cp -f "plasma-widget-cwp_${NEW_VER}.orig.tar.gz" ./TEST/

    cd ./TEST/"plasma-widget-cwp-${NEW_VER}"
    dpkg-buildpackage -rfakeroot
    cd ..

    export LINTIAN_LOG_FILE=../"plasma-widget-cwp-${NEW_VER_FULL}.lintian.log"
    echo " "
    echo "Now running lintian:"
    lintian -ivI plasma-widget-cwp_${NEW_VER_FULL}_i386.changes > ${LINTIAN_LOG_FILE}
    cat ${LINTIAN_LOG_FILE}
    echo "Finished running lintian."
    echo " "
    kwrite ${LINTIAN_LOG_FILE}
    cd ..

        ;;
esac


kwrite "plasma-widget-cwp-${NEW_VER}/debian/changelog"

dput -f ubuntu plasma-widget-cwp_${NEW_VER}${SFX}${UBUNTU_SFX}_source.changes
dput -f ubuntu plasma-widget-cwp_${NEW_VER}${SFX}~maverick1_source.changes
dput -f ubuntu plasma-widget-cwp_${NEW_VER}${SFX}~lucid1_source.changes
dput -f ubuntu plasma-widget-cwp_${NEW_VER}${SFX}~karmic1_source.changes
dput -f ubuntu plasma-widget-cwp_${NEW_VER}${SFX}~jaunty1_source.changes

cp -fr "plasma-widget-cwp-${NEW_VER}/debian" ../

echo "Update finished successfully"

