#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"

export PACKAGE="qtcurve"

# Uncomment if necessary:
export SFX="-4"

#export NEW_VER=1.9

export A_TYPE="xz"

# experimental unstable
export MAIN_DIST="unstable"


# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"


# Get old version
GetOldVersion


# Get new version
if GetNewVersion "${@}"; then
    # VER_LIST=$(curl "https://cgit.kde.org/qtcurve.git/refs/tags" 2>&1 | sed -ne "s|^.*'/qtcurve.git/tag/?h=\([0-9\.]*\)'>.*$|\1|p")
    VER_LIST=$(curl "https://download.kde.org/stable/qtcurve/" 2>&1 | sed -ne "s|^.*<a href=\"qtcurve-\([0-9\.]*\)\.tar\.xz\">.*$|\1|p")
    NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
fi
export NEW_VER_FULL=${NEW_VER}${SFX}



# Display versions
DisplayVersions "https://download.kde.org/stable/qtcurve/"



# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get sources
GetSourcesUsingUscan


# Launch common script for updating of packages
source "${MAIN_DIR}/Debian/updating_packages"

