#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="qtcurve"

# Uncomment if necessary:
export SFX="-6"

export NEW_VER=1.8.18+git20160320-3d8622c

export A_TYPE="gz"

# experimental unstable
export MAIN_DIST="unstable"


# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"


# Get old version
GetOldVersion


# Get new version
if GetNewVersion "${@}"; then
    PROJECT=qtcurve
    VER_LIST=$(curl "https://cgit.kde.org/${PROJECT}.git/refs/tags" 2>&1 | sed -ne "s|^.*'/${PROJECT}.git/tag/?h=\([0-9\.]*\)'>.*$|\1|p")
    NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
fi
export NEW_VER_FULL=${NEW_VER}${SFX}



# Display versions
DisplayVersions "https://cgit.kde.org/qtcurve.git"



# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get sources
GetSources


# Launch common script for updating of packages
source "${MAIN_DIR}/Debian/updating_packages"

