#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="qtcurve"

# Uncomment if necessary:
# export SFX="-6"

export NEW_VER=1.8.18+git20160112-0cd6aae

export A_TYPE="gz"

# experimental unstable
export MAIN_DIST="unstable"


# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"


# Get old version
GetOldVersion


# Find new version
export PROJECT=qtcurve
export VER_LIST=$(curl "https://quickgit.kde.org/?p=${PROJECT}.git&a=tags" 2>&1 | sed -ne "s|^.*href=\"http://quickgit.kde.org/?p=${PROJECT}.git&amp;a=tag&amp;t=\(.*[0-9]\)\">tag.*|\1|p")
if [ -z "${NEW_VER=}" ]; then
    export NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
fi
export NEW_VER_FULL=${NEW_VER}${SFX}



# Display versions
DisplayVersions "https://quickgit.kde.org/?p=${PROJECT}.git"



# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get sources
GetSources


# Launch common script for updating packages and uploading them to mentors.debian.net
source "${MAIN_DIR}/Debian/updating_packages"

