#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="ncdc-devel"

export REMOTE_BRANCH="stable/master"

source "${MAIN_DIR}/Launchpad/compare_with_package_in_Debian"
