#!/bin/bash


if [ -z "${MAIN_DIR}" ]; then
    export MAIN_DIR="${PWD}/$(dirname ${0})/../.."
fi

export PACKAGE="q4wine-unstable"

# Uncomment if necessary:
#export SFX="-0ppa6"


# Launch common script for setting variables
source "${MAIN_DIR}/Launchpad/setting_variables"


# Get old version
GetOldVersion
export OLD_COMMIT=$(echo ${OLD_VER} | sed -e "s/^.*-[0-9]\{6,6\}-\(.*\)$/\1/")


# Find new version
export LAST_SRC_INFO=$(curl -I https://nodeload.github.com/brezerk/q4wine/tarball/master 2>&1)
export LAST_SRC=$(echo "${LAST_SRC_INFO}" | grep 'Content-Disposition:' | sed -e "s/.*\(brezerk-q4wine.*\).tar.gz.*/\1/")
export LAST_COMMIT=$(echo "${LAST_SRC}" | sed -e "s/^brezerk-q4wine.*-[0-9]\+-g\(.*\)$/\1/")


export CUR_VER=$(curl -k "https://raw.github.com/brezerk/q4wine/master/src/CMakeLists.txt" 2>&1 | grep "SET(APP_VERSION" | sed -e "s/^SET(APP_VERSION \"\([0-9]\+\.[0-9]\+\).*\")$/\1/")
export DATE=$(date "+%Y%m%d-%H%M%S")
export NEW_VER="${CUR_VER}-${DATE}-${LAST_COMMIT}"
export NEW_VER_FULL="${NEW_VER}${SFX}${UBUNTU_SFX}"


# Display versions
DisplayVersionsUnstable


# Print versions
PrintVersionsUnstable "${@}"


# Check versions
CheckVersionsUnstable


# Get the sources
if !([ -e "${LAST_SRC}.tar.gz" ]); then
    rm -f master*
    # -4 wget https://github.com/brezerk/q4wine/tarball/master
    wget -4 https://nodeload.github.com/brezerk/q4wine/tarball/master
    rm -f brezerk-q4wine-*.tar.gz*
    mv master "${LAST_SRC}.tar.gz"
fi

if !([ -e "${LAST_SRC}.tar.gz" ]); then
    echo "File ${LAST_SRC}.tar.gz is not found.";
    exit 0;
fi

if !([ -e "${PACKAGE}_${NEW_VER}.orig.tar.xz" ]); then
    tar xzf "${LAST_SRC}".tar.gz
    mv "brezerk-q4wine-${LAST_COMMIT}" "${PACKAGE}-${NEW_VER}"
    tar -cJf "${PACKAGE}_${NEW_VER}.orig.tar.xz" "${PACKAGE}-${NEW_VER}"
fi


export UPDATE_STRING="Minor update from GIT master branch."

export DESTINATION="q4wine"

export A_TYPE="xz"
export D_ARGS="xJf"

# Launch common script for updating packages and uploading them to Launchpad
source "${MAIN_DIR}/Launchpad/updating_packages"

