#!/bin/bash


if [ -z "${MAIN_DIR}" ]; then
    export MAIN_DIR="${PWD}/$(dirname ${0})/../.."
fi

export PACKAGE="q4wine-unstable"

# Uncomment if necessary:
#export SFX="-0ppa6"


# Launch common script for setting variables
source "${MAIN_DIR}/Launchpad/setting_variables"


# Get old version
export OLD_VER_FULL=$(head -n 1 "${PKG_DIR}/${PACKAGE}-debian/debian/changelog" | sed -e "s/.* (\(.*\)) .*/\1/")
export OLD_VER=$(echo ${OLD_VER_FULL} | sed -e "s/^\(.*\)-0ppa.*$/\1/")
export OLD_SFX=$(echo ${OLD_VER_FULL} | sed -e "s/^.*\(-[0-9]ppa[0-9]\).*$/\1/")
export OLD_COMMIT=$(echo ${OLD_VER} | sed -e "s/^.*-[0-9]\{6,6\}-\(.*\)$/\1/")


# Find new version
export LAST_SRC_INFO=$(curl -I https://nodeload.github.com/brezerk/q4wine/tarball/master 2>&1)
export LAST_SRC=$(echo "${LAST_SRC_INFO}" | grep 'Content-Disposition:' | sed -e "s/.*\(brezerk-q4wine.*\).tar.gz.*/\1/")
export LAST_COMMIT=$(echo "${LAST_SRC}" | sed -e "s/^brezerk-q4wine.*-[0-9]\+-g\(.*\)$/\1/")


echo "Old  commit ID: ${OLD_COMMIT}"
echo "Last commit ID: ${LAST_COMMIT}"


export CUR_VER=$(curl -k "https://raw.github.com/brezerk/q4wine/master/src/CMakeLists.txt" 2>&1 | grep "SET(APP_VERSION" | sed -e "s/^SET(APP_VERSION \"\([0-9]\+\.[0-9]\+\).*\")$/\1/")
export DATE=$(date "+%Y%m%d-%H%M%S")
export NEW_VER="${CUR_VER}-${DATE}-${LAST_COMMIT}"
export NEW_VER_FULL="${NEW_VER}${SFX}${UBUNTU_SFX}"


# Display versions
echo "OLD_VER_FULL = ${OLD_VER_FULL}"
echo "NEW_VER_FULL = ${NEW_VER_FULL}"


# Check versions
if [ -z "${OLD_COMMIT}" ]; then
    echo "OLD_COMMIT is empty!";
    exit 0;
elif [ -z "${LAST_COMMIT}" ]; then
    echo "LAST_COMMIT is empty!";
    exit 0;
elif [ -z ${CUR_VER} ]; then
    echo "CUR_VER is empty!";
    exit 0;
else
    if !([ "${LAST_COMMIT}" = "${OLD_COMMIT}" ]); then
        if !([ "${SFX}" = "-0ppa1" ]); then
            echo "Now SFX = ${SFX} but must be '-0ppa1' for a new release!";
            exit 0;
        fi
    else
        if ([ "${SFX}" = "-0ppa1" ]); then
            echo "Upgrading is not required.";
            exit 0;
        fi
    fi
fi


# Get the sources
if !([ -e "${LAST_SRC}.tar.gz" ]); then
    rm -f master*
    # -4 wget https://github.com/brezerk/q4wine/tarball/master
    wget -4 https://nodeload.github.com/brezerk/q4wine/tarball/master

    rm -f brezerk-q4wine-*.tar.gz*
    mv master "${LAST_SRC}.tar.gz"
fi

if !([ -e "${LAST_SRC}.tar.gz" ]); then
    echo "File ${LAST_SRC}.tar.gz is not found.";
    exit 0;
fi

if !([ -e "${PACKAGE}_${NEW_VER}.orig.tar.gz" ]); then
    tar xzf "${LAST_SRC}".tar.gz
    mv "brezerk-q4wine-${LAST_COMMIT}" "${PACKAGE}-${NEW_VER}"
    tar -cjf "${PACKAGE}_${NEW_VER}.orig.tar.bz2" "${PACKAGE}-${NEW_VER}"
fi


export UPDATE_STRING="Minor update from GIT master branch."

export DESTINATION="q4wine"

# Launch common script for updating packages and uploading them to Launchpad
source "${MAIN_DIR}/Launchpad/updating_packages"

