#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="astromenace"

# Uncomment if necessary:
# export SFX="-6"

export RPKGD="+repack"

export NEW_VER=1.3.2+repack

export A_TYPE="xz"
#export A_TYPE="gz"


# experimental unstable
export MAIN_DIST="unstable"

# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"


# Get old version
GetOldVersion


# Get new version
DEVELOPER=viewizard
PROJECT=astromenace
if GetNewVersion "${@}"; then
    VER_LIST=$(curl "https://github.com/${DEVELOPER}/${PROJECT}/tags" 2>&1 | sed -ne "s:^.*\"/${DEVELOPER}/${PROJECT}/archive/refs/tags/v\(.*\).tar.gz\" .*:\1:p")
    CUR_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
    NEW_VER=${CUR_VER}${RPKGD}
fi
export NEW_VER_FULL=${NEW_VER}${SFX}


# Display versions
DisplayVersions "https://github.com/${DEVELOPER}/${PROJECT}/tags"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get sources
GetSources


#export DIR_NAME="AstroMenace"
#export OLD_DIR_NAME="AstroMenace"

# Launch common script for updating of packages
source "${MAIN_DIR}/Debian/updating_packages"

