#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="q4wine"

# Uncomment if necessary:
#export SFX="-2"

# experimental unstable
export MAIN_DIST="unstable"


# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"


# Get old version
GetOldVersion


# Get new version
DEVELOPER=brezerk
PROJECT=q4wine
if GetNewVersion "${@}"; then
    # VER_LIST=$(curl 'https://sourceforge.net/projects/q4wine/files/q4wine/' 2>&1 | sed -ne "s:^.*<tr title=\"q4wine \(.*\)\" class=\"folder \">.*$:\1:p")
    VER_LIST=$(curl "https://github.com/${DEVELOPER}/${PROJECT}/tags" 2>&1 | sed -ne "s:^.*\"/${DEVELOPER}/${PROJECT}/archive/refs/tags/v\(.*\).tar.gz\" .*:\1:p")
    NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
fi
export NEW_VER_FULL=${NEW_VER}${SFX}


# Display versions
DisplayVersions "https://sourceforge.net/projects/q4wine/files/q4wine/"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get sources
GetSourcesUsingUscan


# Launch common script for updating of packages
source "${MAIN_DIR}/Debian/updating_packages"

