#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export MAIN_DIST="wheezy-backports-sloppy"

export BPO_SFX="~bpo7+1"

# export BPO_VER=1.3.1-1

export BASIC_VER=1.3-1


source "$(dirname ${0})/backport_q4wine"

