#!/bin/sh

export DEBEMAIL="Boris Pek <tehnick-8@mail.ru>"

cd "${HOME}/WorkDir/Devel/EiskaltDC++/Launchpad/"

# apt-get source eiskaltdcpp-unstable

if !([ -e eiskaltdcpp-unstable_*.orig.tar.gz ]); then
  echo "File eiskaltdcpp-unstable_*.orig.tar.gz is not found.";
  exit 0;
fi

export OLD_COMMIT=$(ls eiskaltdcpp-unstable_*.orig.tar.gz | sed -e "s/^eiskaltdcpp-unstable_.*-\(.*\).orig.tar.gz$/\1/")

export LAST_SRC_INFO=$(curl -v http://nodeload.github.com/negativ/eiskaltdcpp/tarball/master 2>&1)
export LAST_SRC=$(echo "${LAST_SRC_INFO}" | grep 'Location: ' | sed -e "s/.*\(negativ-eiskaltdcpp.*\).tar.gz.*/\1/")
export LAST_COMMIT=$(echo "${LAST_SRC}" | sed -e "s/^negativ-eiskaltdcpp.*-[0-9]\+-g\(.*\)$/\1/")

echo "Old  commit ID: ${OLD_COMMIT}"
echo "Last commit ID: ${LAST_COMMIT}"

if [ -z "${OLD_COMMIT}" ]; then
  echo "Error: number of old commit is empty!";
  exit 0;
elif [ -z "${LAST_COMMIT}" ]; then
  echo "Error: number of last commit is empty!";
  exit 0;
elif [ "${OLD_COMMIT}" = "${LAST_COMMIT}" ]; then
  echo "Upgrading is not required.";
  exit 0;
fi

if !([ -e "${LAST_SRC}.tar.gz" ]); then
  rm master*
  # wget http://github.com/negativ/eiskaltdcpp/tarball/master
  wget http://nodeload.github.com/negativ/eiskaltdcpp/tarball/master

  rm negativ-eiskaltdcpp-*.tar.gz*
  mv master "${LAST_SRC}.tar.gz"
fi

if !([ -e negativ-eiskaltdcpp-*.tar.gz ]); then
  echo "File negativ-eiskaltdcpp-*.tar.gz is not found.";
  exit 0;
fi

echo "Updating is started."

tar xzf "${LAST_SRC}".tar.gz

export OLD_VER=$(ls eiskaltdcpp-unstable_*.orig.tar.gz | sed -e "s/^eiskaltdcpp-unstable_\(.*\).orig.tar.gz$/\1/")

export DATE=$(date "+%Y%m%d-%H%M%S")
export CUR_VER=$(cat "negativ-eiskaltdcpp-${LAST_COMMIT}/CMakeLists.txt" | grep "set (VERSION " | sed -e "s/^.*VERSION \"\(.*\+\)\")$/\1/")
export NEW_VER="${CUR_VER}-${DATE}-${LAST_COMMIT}"

cat "negativ-eiskaltdcpp-${LAST_COMMIT}/CMakeLists.txt" | grep "set (VERSION "
echo "OLD_VER = ${OLD_VER}"
echo "NEW_VER = ${NEW_VER}"

if [ -z ${CUR_VER} ]; then
  echo "Error: number of current version is empty!";
  exit 0;
fi

mv "negativ-eiskaltdcpp-${LAST_COMMIT}" "eiskaltdcpp-unstable-${NEW_VER}"
tar -czf "eiskaltdcpp-unstable_${NEW_VER}.orig.tar.gz" "eiskaltdcpp-unstable-${NEW_VER}"

mv "eiskaltdcpp-unstable-${OLD_VER}/debian" "eiskaltdcpp-unstable-${NEW_VER}/"
rm -r "eiskaltdcpp-unstable-${OLD_VER}" eiskaltdcpp-unstable_${OLD_VER}*

cd "eiskaltdcpp-unstable-${NEW_VER}"

# If you want to build package on your system uncomment this:
# dch -v "${NEW_VER}-mybuild1" "Minor update."
# dpkg-buildpackage -rfakeroot

# Note: I am using gnupg-agent for comfortable work

# begin update for basic releases
dch -b --force-distribution --distribution "natty" -v "${NEW_VER}-0ppa1~natty1" \
  "Minor update."
debuild -S -sa
# end update for basic releases

# Full list: hardy intrepid jaunty karmic lucid maverick natty
# But not all of them are available, see: https://launchpad.net/ubuntu/+ppas
# begin update for other releases
cp debian/changelog ../changelog # copy basic changelog

cp -f ../changelog debian/changelog
dch -b --force-distribution --distribution "maverick" -v "${NEW_VER}-0ppa1~maverick1" \
  "Automated backport upload; no source changes."
debuild -S -sd

cp -f ../changelog debian/changelog
dch -b --force-distribution --distribution "lucid" -v "${NEW_VER}-0ppa1~lucid1" \
  "Automated backport upload; no source changes."
debuild -S -sd

cp -f ../changelog debian/changelog
dch -b --force-distribution --distribution "karmic" -v "${NEW_VER}-0ppa1~karmic1" \
  "Automated backport upload; no source changes."
debuild -S -sd

mv debian/source ../ # make dirty hack

cp -f ../changelog debian/changelog
dch -b --force-distribution --distribution "jaunty" -v "${NEW_VER}-0ppa1~jaunty1" \
  "Automated backport upload; no source changes."
debuild -S -sd

mv ../source debian/ # rollback dirty hack

mv ../changelog debian/changelog # rollback basic changelog
# end update for other releases

cd ..
dput -f ubuntu eiskaltdcpp-unstable_${NEW_VER}-0ppa1~natty1_source.changes
dput -f ubuntu eiskaltdcpp-unstable_${NEW_VER}-0ppa1~maverick1_source.changes
dput -f ubuntu eiskaltdcpp-unstable_${NEW_VER}-0ppa1~lucid1_source.changes
dput -f ubuntu eiskaltdcpp-unstable_${NEW_VER}-0ppa1~karmic1_source.changes
dput -f ubuntu eiskaltdcpp-unstable_${NEW_VER}-0ppa1~jaunty1_source.changes

echo "Update finished successfully"

