#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="eiskaltdcpp"

# Uncomment if necessary:
export SFX="-1ppa2"

export NEW_VER=2.2.10+340+g44d8aea4

export A_TYPE="xz"


# Launch common script for setting variables
source "${MAIN_DIR}/Launchpad/setting_variables"


# Get old version
GetOldVersion


# Get new version
if GetNewVersion "${@}"; then
    VER_LIST=$(curl 'https://sourceforge.net/projects/eiskaltdcpp/files/Sources/' 2>&1 | sed -ne "s:^.*Sources/eiskaltdcpp-\(.*\).tar.xz/download.*$:\1:p")
    NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
fi
export NEW_VER_FULL=${NEW_VER}${SFX}${UBUNTU_SFX}


# Display versions
DisplayVersions "https://sourceforge.net/projects/eiskaltdcpp/files/Sources/"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get sources
GetSourcesUsingUscan


export DESTINATION="direct-connect"

# Launch common script for updating of packages and uploading them to Launchpad
source "${MAIN_DIR}/Launchpad/updating_packages"

