#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="q4wine-qt4"

# Uncomment if necessary:
# export SFX="-1ppa1"


# Launch common script for setting variables
source "${MAIN_DIR}/Launchpad/setting_variables"
export MAIN_DIST="vivid"
export UBUNTU_SFX="~${MAIN_DIST}1"


# Get old version
GetOldVersion


# Find new version
export VER_LIST=$(curl 'https://sourceforge.net/projects/q4wine/files/q4wine/' 2>&1 | sed -ne "s:^.*<tr title=\"q4wine \(.*\)\" class=\"folder \">.*$:\1:p")
export NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
export NEW_VER_FULL=${NEW_VER}${SFX}${UBUNTU_SFX}


# Display versions
DisplayVersions "https://sourceforge.net/projects/q4wine/files/q4wine/"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get sources
GetSources
mv "q4wine_${NEW_VER}.orig.tar.${A_TYPE}" "${PACKAGE}_${NEW_VER}.orig.tar.${A_TYPE}"


export UPDATE_STRING="Backport to Ubuntu Wily."

export DESTINATION="q4wine"

export DIST_LIST="trusty
                  precise"

export DIR_NAME="q4wine-${NEW_VER}"
export OLD_DIR_NAME="q4wine-${OLD_VER}"

# Launch common script for updating packages and uploading them to Launchpad
source "${MAIN_DIR}/Launchpad/updating_packages"

