#!/bin/bash


if [ -z "${MAIN_DIR}" ]; then
    export MAIN_DIR="${PWD}/$(dirname ${0})/../.."
fi

export PACKAGE="libterm-shellui-perl"

# Uncomment if necessary:
#export SFX="-1ppa1"

# Launch common script for setting variables
source "${MAIN_DIR}/Launchpad/setting_variables"


# Get old version
GetOldVersion


# Find new version
export DEVELOPER=BRONSON
export PROJECT=Term-ShellUI
export VER_LIST=$(curl "http://search.cpan.org/dist/${PROJECT}/" 2>&1 | grep "/CPAN/authors/id/" | grep "${DEVELOPER}/${PROJECT}-" | sed -e "s:^.*/${DEVELOPER}/${PROJECT}-\(.*\).tar.gz.*:\1:")
export NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
export NEW_VER_FULL=${NEW_VER}${SFX}${UBUNTU_SFX}


# Display versions
DisplayVersions "http://search.cpan.org/dist/${PROJECT}/"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get the sources
if !([ -e "${PACKAGE}_${NEW_VER}.orig.tar.gz" ]); then
    wget -4 -c "http://search.cpan.org/CPAN/authors/id/B/BR/${DEVELOPER}/${PROJECT}-${NEW_VER}.tar.gz"
    mv -f "${PROJECT}-${NEW_VER}.tar.gz" "${PACKAGE}_${NEW_VER}.orig.tar.gz"
fi


export UPDATE_STRING="Update to stable release ${NEW_VER}."

export DIR_NAME="${PROJECT}-${NEW_VER}"
export OLD_DIR_NAME="${PROJECT}-${OLD_VER}"

# Launch common script for updating packages and uploading them to Launchpad
source "${MAIN_DIR}/Launchpad/updating_packages_old"

