#!/bin/bash


if [ -z "${MAIN_DIR}" ]; then
    export MAIN_DIR="${PWD}/$(dirname ${0})/../.."
fi

export PACKAGE="kde-style-qtcurve"

# Uncomment if necessary:
#export SFX="-2"

#export NEW_VER=1.8.12

# experimental unstable
export MAIN_DIST="unstable"


# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"


# Get old version
GetOldVersion


# Find new version
export VER_LIST=$(curl "http://www.kde-look.org/content/download.php?content=40492&id=1" 2>&1 | grep "/QtCurve-KDE4-" | sed -e "s:^.*/QtCurve-KDE4-\(.*\).tar.bz2\".*:\1:")
if [ -z "${NEW_VER=}" ]; then
    export NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
fi
export NEW_VER_FULL=${NEW_VER}${SFX}



# Display versions
DisplayVersions "http://kde-look.org/content/show.php?content=40492"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get the sources
if !([ -e "${PACKAGE}_${NEW_VER}.orig.tar.bz2" ]); then
    wget -4 -c "http://craigd.wikispaces.com/file/view/QtCurve-KDE4-${NEW_VER}.tar.bz2"
    mv -f "QtCurve-KDE4-${NEW_VER}.tar.bz2" "${PACKAGE}_${NEW_VER}.orig.tar.bz2"
fi


export UPDATE_STRING="Update to stable release ${NEW_VER}."

export DIR_NAME="QtCurve-KDE4-${NEW_VER}"
export OLD_DIR_NAME="QtCurve-KDE4-${OLD_VER}"

# Launch common script for updating packages and uploading them to mentors.debian.net
source "${MAIN_DIR}/Debian/updating_packages"

