#!/bin/bash


if [ -z "${MAIN_DIR}" ]; then
    export MAIN_DIR="${PWD}/$(dirname ${0})/../.."
fi

export PACKAGE="qconf"

# Uncomment if necessary:
#export SFX="-2"
export SFX="-3"

# experimental unstable
export MAIN_DIST="unstable"


# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"


# Get old version
GetOldVersion


# Find new version
export VER_LIST=$(curl 'http://delta.affinix.com/download/' 2>&1 | grep 'qconf-' | grep '.tar.bz2' | sed -e "s/^.*qconf-\(.*\).tar.bz2.*$/\1/")
export NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
export NEW_VER_FULL=${NEW_VER}${SFX}


# Display versions
DisplayVersions "http://delta.affinix.com/download/"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get the sources
#if !([ -e "${PACKAGE}_${NEW_VER}.orig.tar.bz2" ]); then
if !([ -e "${PACKAGE}_${NEW_VER}.orig.tar.gz" ]); then
    wget -4 -c "http://delta.affinix.com/download/qconf-${NEW_VER}.tar.bz2"
    #rm -rf "${PACKAGE}-${NEW_VER}"
    #tar xjf "${PACKAGE}-${NEW_VER}.tar.bz2"
    #tar -cjf "${PACKAGE}_${NEW_VER}.orig.tar.bz2" "${PACKAGE}-${NEW_VER}"
    mv -f "${PACKAGE}-${NEW_VER}.tar.bz2" "${PACKAGE}_${NEW_VER}.orig.tar.bz2"
fi


export UPDATE_STRING="Update to stable release ${NEW_VER}."

# Launch common script for updating packages and uploading them to mentors.debian.net
#source "${MAIN_DIR}/Debian/updating_packages"
source "${MAIN_DIR}/Debian/updating_packages_old"

