#!/bin/bash

set -e

export PKG_DIR="${MAIN_DIR}/Launchpad/${PACKAGE}"
export TEMP_DIR="${PKG_DIR}/TEMP"

if [ -z "${REMORE_BRANCH}" ]; then
    export REMORE_BRANCH="origin/master"
fi

if [ -z "${TEST_DIR}" ]; then
    export TEST_DIR="debian"
fi

cd "${PKG_DIR}/${PACKAGE}-debian"
git diff "${REMORE_BRANCH}" ${TEST_DIR} > "${TEMP_DIR}/debian.diff"
kwrite "${TEMP_DIR}/debian.diff" > /dev/null &
