#!/bin/bash

export PKG_DIR="${MAIN_DIR}/Launchpad/${PACKAGE}"
export TEMP_DIR="${PKG_DIR}/TEMP"


rm -rf "${PKG_DIR}/${PACKAGE}-debian/debian-unstable"
cp -rfa "${PKG_DIR}-unstable/${PACKAGE}-unstable-debian/debian" \
       "${PKG_DIR}/${PACKAGE}-debian/debian-unstable"


cd "${PKG_DIR}/${PACKAGE}-debian/debian-unstable"
for FILE_FROM in *-unstable* ; do
    FILE_TO=$(echo ${FILE_FROM} | sed -e "s/-unstable//")
    echo "Moving '${FILE_FROM}' to '${FILE_TO}'"
    mv -f "${FILE_FROM}" "${FILE_TO}"
done


cd "${PKG_DIR}/${PACKAGE}-debian"
diff -urN debian debian-unstable > "${TEMP_DIR}/debian.diff"
kwrite "${TEMP_DIR}/debian.diff" > /dev/null &
