#!/bin/bash
#
# Common script for setting variables

export MAIN_DIST="groovy"
export DIST_LIST="focal eoan bionic xenial"

export UBUNTU_SFX="~${MAIN_DIST}1"
export DEFAULT_SFX="-0ppa1"

export PKG_DIR="${MAIN_DIR}/Launchpad/${PACKAGE}"

[ -z "${SFX}" ] && export SFX="${DEFAULT_SFX}"

source "${MAIN_DIR}/Tools/common_variables.sh" || exit 1
source "${MAIN_DIR}/Tools/common_functions.sh" || exit 1

