#!/bin/bash

# This is the common script for updating packages and uploading them to Launchpad


CheckBasicVariables || exit 1
CheckTarballAvailability || exit 1
DefineTarOptions || exit 1
DefineAdditionalVariables ${@}

ReportStartOfUpdate
PrepareSourcePackage
PrepareDiff
UpdateSourcePackagesForLaunchpad
DoMainChecks

CopyUpdatedChangelogToGit
UploadPackagesToLaunchpad
ReportBuildSuccess
UpdateLocalRepo

