#!/bin/bash

# This is the common script for updating packages and uploading them to Launchpad
#
# It make such actions:
# 1) Update changelog.
# 2) Prepare sources to upload.
#    Build the package and check it using lintian (optional)
# 3) Upload sources to Launchpad


if [ -z "${PACKAGE}" ]; then
    echo "Error: PACKAGE variable is empty!";
    exit 1;
elif [ -z "${NEW_VER}" ]; then
    echo "Error: NEW_VER variable is empty!";
    exit 1;
fi


if !([ -e "${PACKAGE}_${NEW_VER}.orig.tar.bz2" ]); then
    echo "File ${PACKAGE}_${NEW_VER}.orig.tar.bz2 is not found.";
    exit 0;
fi

echo "Updating is started."

export DEBEMAIL="Boris Pek <tehnick-8@mail.ru>"

rm -rf "${PACKAGE}-${NEW_VER}" "${PACKAGE}_${NEW_VER}-"*

tar xjf "${PACKAGE}_${NEW_VER}.orig.tar.bz2"
cp -rf "${PKG_DIR}/${PACKAGE}-debian/debian" "${PACKAGE}-${NEW_VER}/debian"

if ([ -d "${PACKAGE}-${OLD_VER}" ]); then
    diff -ur "${PACKAGE}-${OLD_VER}" "${PACKAGE}-${NEW_VER}" > \
             "${TEMP_DIR}/${OLD_VER_FULL}::${NEW_VER_FULL}.diff"
fi

cd "${TEMP_DIR}/${PACKAGE}-${NEW_VER}"

# If you want to build package on your system uncomment this:
# dch -v "$NEW_VER-mybuild1" "Minor update."
# dpkg-buildpackage -rfakeroot

# Note: I am using gnupg-agent for comfortable work

# Full list of Ubuntu releases:
# hardy intrepid jaunty karmic lucid maverick natty oneiric precise
# But not all of them are available, see: https://launchpad.net/ubuntu/+ppas

# begin update for basic releases
export DIST="${MAIN_DIST}"
if [ "${SFX}" = "-0ppa1" ]; then
    dch -b --force-distribution --distribution "${DIST}" -v "${NEW_VER}${SFX}~${DIST}1" \
        "${UPDATE_STRING}"
    debuild -S -sa || exit 1
else
    dch -b --force-distribution --distribution "${DIST}" -v "${NEW_VER}${SFX}~${DIST}1" \
        "Some fixes in package."
    kwrite debian/changelog
    # debuild -S -sd
    debuild -S -sa || exit 1
fi
# end update for basic releases

# begin update for other releases
cp -f debian/changelog ../changelog # copy basic changelog

if [ -z "${DIST_LIST}" ]; then
    DIST_LIST="oneiric
               natty
               maverick
               lucid
               karmic"
    export DIST_LIST;
fi

for DIST in ${DIST_LIST} ; do
    cp -f ../changelog debian/changelog
    dch -b --force-distribution --distribution "${DIST}" -v "${NEW_VER}${SFX}~${DIST}1" \
        "Automated backport upload; no source changes."
    debuild -S -sd || exit 1
done

mv ../changelog debian/changelog # rollback basic changelog
# end update for other releases


case "${1}" in
        test)

    echo " "
    echo "Now will be tests."
    echo " "

    rm -rf "${TEST_DIR}"
    mkdir -p "${TEST_DIR}" && cd "${TEST_DIR}"

    cp -r "${TEMP_DIR}/${PACKAGE}-${NEW_VER}" "${TEST_DIR}/"
    cp -f "${TEMP_DIR}/${PACKAGE}_${NEW_VER}.orig.tar.bz2" "${TEST_DIR}/"

    export BUILD_LOG_FILE="${TEMP_DIR}/${PACKAGE}-${NEW_VER_FULL}.build.log"
    export WARNINGS_LOG_FILE="${TEMP_DIR}/${PACKAGE}-${NEW_VER_FULL}.warnings.log"
    cd "${TEST_DIR}/${PACKAGE}-${NEW_VER}"
    echo " "
    echo "Start building packages..."
    nice -n19 dpkg-buildpackage -rfakeroot > ${BUILD_LOG_FILE} 2> ${WARNINGS_LOG_FILE}
    echo "Finished building packages."
    echo " "

    export LINTIAN_LOG_FILE="${TEMP_DIR}/${PACKAGE}-${NEW_VER_FULL}.lintian.log"
    cd "${TEST_DIR}"
    echo " "
    echo "Now running lintian:"
    lintian -ivI --pedantic ${PACKAGE}_${NEW_VER_FULL}_*.changes > ${LINTIAN_LOG_FILE}
    cat ${LINTIAN_LOG_FILE} | grep "E: "
    cat ${LINTIAN_LOG_FILE} | grep "W: "
    echo "Finished running lintian."
    echo " "
    kwrite ${LINTIAN_LOG_FILE}

    cd "${TEMP_DIR}/${PACKAGE}-${NEW_VER}"

        ;;
esac


cd "${TEMP_DIR}"
cp -fr "${PACKAGE}-${NEW_VER}/debian" "${PKG_DIR}/${PACKAGE}-debian/"

if [ -z "${DESTINATION}" ]; then
    export DESTINATION="tehnick"
fi

for DIST in ${MAIN_DIST} ${DIST_LIST} ; do
    dput -f ${DESTINATION} ${PACKAGE}_${NEW_VER}${SFX}~${DIST}1_source.changes
done

echo "Update finished successfully"

