#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="libquantum"

# Uncomment if necessary:
export SFX="-6"

#export NEW_VER=1.1.0

export A_TYPE="gz"

# experimental unstable
export MAIN_DIST="unstable"


# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"

# Get old version
GetOldVersion


# Get new version
if GetNewVersion "${@}"; then
    VER_LIST=$(curl 'http://www.libquantum.de/downloads' 2>&1 | sed "s/<a /\n/g" | grep '/files/libquantum-' | sed -e "s:^.*/files/libquantum-\(.*\).tar.gz\".*$:\1:")
    NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
fi
export NEW_VER_FULL=${NEW_VER}${SFX}


# Display versions
DisplayVersions "http://www.libquantum.de/downloads"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get sources
GetSourcesUsingUscan


# Launch common script for updating of packages
source "${MAIN_DIR}/Debian/updating_packages"

