#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="psimedia"

# Uncomment if necessary:
# export SFX="-3ppa1"

#export NEW_VER=1.0.3-git20130306-c2b8446

export A_TYPE="gz"


# Launch common script for setting variables
source "${MAIN_DIR}/Launchpad/setting_variables"
export MAIN_DIST="trusty"
export UBUNTU_SFX="~${MAIN_DIST}1"


# Get old version
GetOldVersion


# Get new version
DEVELOPER=psi-im
PROJECT=psimedia
if GetNewVersion "${@}"; then
    VER_LIST=$(curl "https://github.com/${DEVELOPER}/${PROJECT}/tags" 2>&1 | sed -ne "s:^.*\"/${DEVELOPER}/${PROJECT}/archive/v\(.*\).tar.gz\" .*:\1:p")
    NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
fi
export NEW_VER_FULL=${NEW_VER}${SFX}${UBUNTU_SFX}


# Display versions
DisplayVersions "https://github.com/${DEVELOPER}/${PROJECT}/tags"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get sources
GetSources


export DESTINATION="psi-plus"

export DIST_LIST=" "

# Launch common script for updating of packages and uploading them to Launchpad
source "${MAIN_DIR}/Launchpad/updating_packages"
