#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="psi-translations"

# Uncomment if necessary:
#export SFX="-2"

export NEW_VER=1.12+real1.5

export A_TYPE="gz"

# experimental unstable
export MAIN_DIST="unstable"


# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"


# Get old version
GetOldVersion


# Get new version
DEVELOPER=psi-im
PROJECT=psi-l10n
if GetNewVersion "${@}"; then
    VER_LIST=$(curl "https://github.com/${DEVELOPER}/${PROJECT}/tags" 2>&1 | sed -ne "s:^.*\"/${DEVELOPER}/${PROJECT}/archive/\(.*\).tar.gz\" .*:\1:p")
    NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
fi
export NEW_VER_FULL=${NEW_VER}${SFX}


# Display versions
DisplayVersions "https://github.com/${DEVELOPER}/${PROJECT}/tags"


# Print versions
PrintVersions "${@}"


# Check versions
#CheckVersions


# Get sources
GetSourcesUsingUscan


export DIR_NAME="psi-l10n-1.5"
export OLD_DIR_NAME="psi-translations-1.12"

# Launch common script for updating of packages
source "${MAIN_DIR}/Debian/updating_packages"

