#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="psi-translations"

# Uncomment if necessary:
#export BPO_SFX="~bpo9+2"

#export BPO_VER=1.12+real1.5-4

export BASIC_VER=1.12

export A_TYPE="gz"


# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"
source "${MAIN_DIR}/Debian/setting_variables_for_backports"


# Get old version
GetOldVersion


# Set versions
SetVersions


# Display versions
DisplayVersions


# Get source package
GetSourcePackage


export DIR_NAME="psi-l10n-1.5"

# Launch common script for updating packages and uploading them to mentors.debian.net
source "${MAIN_DIR}/Debian/updating_packages_for_backports"

