#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="qpxtool"

# Uncomment if necessary:
export SFX="-2"

#export NEW_VER=0.8.0

# experimental unstable
export MAIN_DIST="unstable"

# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"


# Get old version
GetOldVersion


# Get new version
if GetNewVersion "${@}"; then
    VER_LIST=$(curl 'https://sourceforge.net/projects/qpxtool/files/qpxtool/0.8.x/' 2>&1 | sed -ne "s:^.*<tr title=\"\(.*\)\" class=\"folder \">.*$:\1:p")
    NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
    [ -z "${NEW_VER}" ] && NEW_VER = OLD_VER
fi
export NEW_VER_FULL=${NEW_VER}${SFX}


# Display versions
DisplayVersions "https://sourceforge.net/projects/qpxtool/files/qpxtool/0.8.x/"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get sources
GetSourcesUsingUscan


#export DIR_NAME="qpxtool-0.7.1_002"
#export OLD_DIR_NAME="qpxtool-0.7.1_002"

# Launch common script for updating of packages
source "${MAIN_DIR}/Debian/updating_packages"

