#!/bin/bash


if [ -z "${MAIN_DIR}" ]; then
    export MAIN_DIR="${PWD}/$(dirname ${0})/../.."
fi

export PACKAGE="yagf"

# Uncomment if necessary:
#export SFX="-2"

# experimental unstable
export MAIN_DIST="unstable"


# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"


# Get old version
GetOldVersion


# Find new version
export PROJECT=yagf
export VER_LIST=$(curl "http://symmetrica.net/cuneiform-linux/yagf-en.html" 2>&1 | grep "yagf-" | grep ".tar.gz" | sed -e "s:^.*${PROJECT}-\(.*\).tar.gz.*:\1:")
export NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
export NEW_VER_FULL=${NEW_VER}${SFX}


# Display versions
DisplayVersions "http://symmetrica.net/cuneiform-linux/yagf-en.html"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get the sources
if !([ -e "${PACKAGE}_${NEW_VER}.orig.tar.gz" ]); then
    wget -4 -c "http://symmetrica.net/cuneiform-linux/${PROJECT}-${NEW_VER}.tar.gz"
    mv -f "${PROJECT}-${NEW_VER}.tar.gz" "${PACKAGE}_${NEW_VER}.orig.tar.gz"
fi


export UPDATE_STRING="Update to stable release ${NEW_VER}."

export DIR_NAME="${PROJECT}-${NEW_VER}"
export OLD_DIR_NAME="${PROJECT}-${OLD_VER}"

# Launch common script for updating packages and uploading them to mentors.debian.net
source "${MAIN_DIR}/Debian/updating_packages_old"

