#!/bin/bash


if [ -z "${MAIN_DIR}" ]; then
    if [[ ${0} =~ ^/.+$ ]]; then
        export MAIN_DIR="$(dirname ${0})/../.."
    else
        export MAIN_DIR="${PWD}/$(dirname ${0})/../.."
    fi
fi

export PACKAGE="yagf"

# Uncomment if necessary:
#export SFX="-2"

# Temporary:
#export NEW_VER=0.9+svn247

# experimental unstable
export MAIN_DIST="unstable"


# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"


# Get old version
GetOldVersion


# Find new version
export PROJECT=yagf
export VER_LIST=$(curl "http://symmetrica.net/cuneiform-linux/yagf-en.html" 2>&1 | sed -ne "s:^.*${PROJECT}-\(.*\).tar.gz.*:\1:p")
if [ -z "${NEW_VER=}" ]; then
    export NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
fi
export NEW_VER_FULL=${NEW_VER}${SFX}


# Display versions
DisplayVersions "http://symmetrica.net/cuneiform-linux/yagf-en.html"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get the sources
if [ ! -e "${PACKAGE}_${NEW_VER}.orig.tar.gz" ]; then
    "${PKG_DIR}/${PACKAGE}-debian/debian/rules" "get-orig-source"
fi


export UPDATE_STRING="Update to stable release ${NEW_VER}."

export DIR_NAME="${PROJECT}-${NEW_VER}"
export OLD_DIR_NAME="${PROJECT}-${OLD_VER}"

export A_TYPE="gz"
export D_ARGS="xzf"

export DM_FLAG="true"

# Launch common script for updating packages and uploading them to mentors.debian.net
source "${MAIN_DIR}/Debian/updating_packages"

