#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="yagf"

# Uncomment if necessary:
# export BPO_SFX="~bpo10+2"

#export BPO_VER=0.9.5+repack1-1

export BASIC_VER=0.9.3.2-1

# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"
source "${MAIN_DIR}/Debian/setting_variables_for_backports"


# Get old version
GetOldVersion


# Set versions
SetVersions


# Display versions
DisplayVersions


# Get sources from Debian repo
if [ ! -e "${PACKAGE}_${PKG_VER}.orig.tar.gz" ]; then
    dget -d http://ftp.de.debian.org/debian/pool/main/y/${PACKAGE}/${PACKAGE}_${PKG_VER_FULL}.dsc
fi

export A_TYPE="gz"
export D_ARGS="xzf"


# Launch common script for updating packages and uploading them to mentors.debian.net
source "${MAIN_DIR}/Debian/updating_packages_for_backports"

