#!/bin/bash

[ -z "${MAIN_DIR}" ] && export MAIN_DIR="$(realpath -s $(dirname ${0})/../..)"


export PACKAGE="libterm-shellui-perl"

# Uncomment if necessary:
export SFX="-2"

export A_TYPE="gz"

# experimental unstable
export MAIN_DIST="unstable"


# Launch common script for setting variables
source "${MAIN_DIR}/Debian/setting_variables"


# Get old version
GetOldVersion


# Get new version
if GetNewVersion "${@}"; then
    DEVELOPER=BRONSON
    PROJECT=Term-ShellUI
    VER_LIST=$(curl "http://search.cpan.org/dist/${PROJECT}/" 2>&1 | sed -ne "s:^.*/${DEVELOPER}/${PROJECT}-\(.*\).tar.gz.*:\1:p")
    NEW_VER=$(echo "${VER_LIST}" | sort -r -V | head -n1)
fi
export NEW_VER_FULL=${NEW_VER}${SFX}


# Display versions
DisplayVersions "http://search.cpan.org/dist/Term-ShellUI/"


# Print versions
PrintVersions "${@}"


# Check versions
CheckVersions


# Get sources
GetSources


export DIR_NAME="${PROJECT}-${NEW_VER}"
export OLD_DIR_NAME="${PROJECT}-${OLD_VER}"


# Launch common script for updating of packages
source "${MAIN_DIR}/Debian/updating_packages"

